package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// CreateAlbum is the resolver for the createAlbum field.
func (r *mutationResolver) CreateAlbum(ctx context.Context, name string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.CreateAlbum(ctx, models.NewRecordID("user", claim.Subject), name)
}

// RenameAlbum is the resolver for the renameAlbum field.
func (r *mutationResolver) RenameAlbum(ctx context.Context, id string, name string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.RenameAlbum(ctx, models.NewRecordID("album", id), models.NewRecordID("user", claim.Subject), name)
}

// DeleteAlbum is the resolver for the deleteAlbum field.
func (r *mutationResolver) DeleteAlbum(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}
	return r.store.Albums.DeleteAlbum(ctx, models.NewRecordID("album", id), models.NewRecordID("user", claim.Subject))
}

// AddFileToAlbum is the resolver for the addFileToAlbum field.
func (r *mutationResolver) AddFileToAlbum(ctx context.Context, albumID string, fileIds []string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.AddFileToAlbum(ctx, models.NewRecordID("album", albumID), models.NewRecordID("user", claim.Subject), fileRecordIDs(fileIds))
}

// RemoveFileFromAlbum is the resolver for the removeFileFromAlbum field.
func (r *mutationResolver) RemoveFileFromAlbum(ctx context.Context, albumID string, fileIds []string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.RemoveFileFromAlbum(ctx, models.NewRecordID("album", albumID), models.NewRecordID("user", claim.Subject), fileRecordIDs(fileIds))
}

// SetFileFavorite is the resolver for the setFileFavorite field.
func (r *mutationResolver) SetFileFavorite(ctx context.Context, id string, favorite bool) (*gql_model.File, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.SetFileFavorite(ctx, models.NewRecordID("file", id), models.NewRecordID("user", claim.Subject), favorite)
}

// Albums is the resolver for the albums field.
func (r *queryResolver) Albums(ctx context.Context) ([]*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.ListAlbums(ctx, models.NewRecordID("user", claim.Subject))
}

// Album is the resolver for the album field.
func (r *queryResolver) Album(ctx context.Context, id string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.GetAlbum(ctx, models.NewRecordID("album", id), models.NewRecordID("user", claim.Subject))
}

// AlbumFile is the resolver for the albumFile field.
func (r *queryResolver) AlbumFile(ctx context.Context, id string, sort []*gql_model.FileSort, limit *int, offset *int) ([]*gql_model.File, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	l, o := filePaging(limit, offset)
	return r.store.ListAlbumFile(ctx, models.NewRecordID("album", id), models.NewRecordID("user", claim.Subject), sort, l, o)
}

// FavoriteFile is the resolver for the favoriteFile field.
func (r *queryResolver) FavoriteFile(ctx context.Context, sort []*gql_model.FileSort, limit *int, offset *int) ([]*gql_model.File, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	l, o := filePaging(limit, offset)
	return r.store.ListFavoriteFile(ctx, models.NewRecordID("user", claim.Subject), sort, l, o)
}
