package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// CreateAlbum is the resolver for the createAlbum field.
func (r *mutationResolver) CreateAlbum(ctx context.Context, name string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.CreateAlbum(ctx, models.NewRecordID("user", claim.Subject), name)
}

// RenameAlbum is the resolver for the renameAlbum field.
func (r *mutationResolver) RenameAlbum(ctx context.Context, id string, name string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.RenameAlbum(ctx, models.NewRecordID("album", id), models.NewRecordID("user", claim.Subject), name)
}

// DeleteAlbum is the resolver for the deleteAlbum field.
func (r *mutationResolver) DeleteAlbum(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}
	return r.store.Albums.DeleteAlbum(ctx, models.NewRecordID("album", id), models.NewRecordID("user", claim.Subject))
}

// AddMediaToAlbum is the resolver for the addMediaToAlbum field.
func (r *mutationResolver) AddMediaToAlbum(ctx context.Context, albumID string, mediaIds []string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.AddMediaToAlbum(ctx, models.NewRecordID("album", albumID), models.NewRecordID("user", claim.Subject), mediaRecordIDs(mediaIds))
}

// RemoveMediaFromAlbum is the resolver for the removeMediaFromAlbum field.
func (r *mutationResolver) RemoveMediaFromAlbum(ctx context.Context, albumID string, mediaIds []string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.RemoveMediaFromAlbum(ctx, models.NewRecordID("album", albumID), models.NewRecordID("user", claim.Subject), mediaRecordIDs(mediaIds))
}

// SetMediaFavorite is the resolver for the setMediaFavorite field.
func (r *mutationResolver) SetMediaFavorite(ctx context.Context, id string, favorite bool) (*gql_model.Media, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.SetMediaFavorite(ctx, models.NewRecordID("media", id), models.NewRecordID("user", claim.Subject), favorite)
}

// Albums is the resolver for the albums field.
func (r *queryResolver) Albums(ctx context.Context) ([]*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.ListAlbums(ctx, models.NewRecordID("user", claim.Subject))
}

// Album is the resolver for the album field.
func (r *queryResolver) Album(ctx context.Context, id string) (*gql_model.Album, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Albums.GetAlbum(ctx, models.NewRecordID("album", id), models.NewRecordID("user", claim.Subject))
}

// AlbumMedia is the resolver for the albumMedia field.
func (r *queryResolver) AlbumMedia(ctx context.Context, id string, sort []*gql_model.MediaSort, limit *int, offset *int) ([]*gql_model.Media, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	l, o := mediaPaging(limit, offset)
	return r.store.ListAlbumMedia(ctx, models.NewRecordID("album", id), models.NewRecordID("user", claim.Subject), sort, l, o)
}

// FavoriteMedia is the resolver for the favoriteMedia field.
func (r *queryResolver) FavoriteMedia(ctx context.Context, sort []*gql_model.MediaSort, limit *int, offset *int) ([]*gql_model.Media, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	l, o := mediaPaging(limit, offset)
	return r.store.ListFavoriteMedia(ctx, models.NewRecordID("user", claim.Subject), sort, l, o)
}
