package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/neoworks/auth/storage/database"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input gql_model.CreateEventInput) (*gql_model.Event, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	owner := models.NewRecordID("user", claim.Subject)
	event, err := r.store.Events.Create(ctx, &database.CreateEventParams{
		Owner:  owner,
		UID:    newUID(),
		Fields: eventFieldsFromCreate(input),
	})
	if err != nil {
		return nil, err
	}
	r.syncEventInvites(ctx, event, claim.Subject, input.Participants)
	return event, nil
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, id string, input gql_model.UpdateEventInput) (*gql_model.Event, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	event, err := r.store.Events.Update(ctx, &database.UpdateEventParams{
		ID:     models.NewRecordID("event", id),
		UserID: models.NewRecordID("user", claim.Subject),
		Fields: eventFieldsFromUpdate(input),
	})
	if err != nil {
		return nil, err
	}
	// Only reconcile invites when the caller sent a participant list; a partial
	// update that omits it must leave existing invites untouched.
	if input.Participants != nil {
		r.syncEventInvites(ctx, event, event.OwnerID, input.Participants)
	}
	return event, nil
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}
	if err := r.store.Events.Delete(ctx,
		models.NewRecordID("event", id),
		models.NewRecordID("user", claim.Subject),
	); err != nil {
		return false, err
	}
	return true, nil
}

// RespondToEventInvite is the resolver for the respondToEventInvite field.
func (r *mutationResolver) RespondToEventInvite(ctx context.Context, eventID string, accept bool) (*gql_model.Event, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	eventRef := models.NewRecordID("event", eventID)
	event, err := r.store.Events.RespondToInvite(ctx, eventRef, models.NewRecordID("user", claim.Subject), accept)
	if err != nil {
		return nil, err
	}
	// Let the owner know how the invitee responded.
	if ownerID, ownerErr := r.store.Events.OwnerOf(ctx, eventRef); ownerErr == nil && ownerID != claim.Subject {
		verb := "declined"
		if accept {
			verb = "accepted"
		}
		title := eventID
		if event != nil {
			title = event.Title
		}
		_, _ = r.notify(ctx, ownerID, "Invitation "+verb, claim.Subject+" "+verb+" \""+title+"\"", nil)
	}
	return event, nil
}

// CreateCalendar is the resolver for the createCalendar field.
func (r *mutationResolver) CreateCalendar(ctx context.Context, input gql_model.CreateCalendarInput) (*gql_model.Calendar, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	isDefault := false
	if input.IsDefault != nil {
		isDefault = *input.IsDefault
	}
	return r.store.Calendars.Create(ctx, &database.CreateCalendarParams{
		Owner:     models.NewRecordID("user", claim.Subject),
		Name:      input.Name,
		Color:     input.Color,
		IsDefault: isDefault,
	})
}

// UpdateCalendar is the resolver for the updateCalendar field.
func (r *mutationResolver) UpdateCalendar(ctx context.Context, id string, input gql_model.UpdateCalendarInput) (*gql_model.Calendar, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Calendars.Update(ctx, &database.UpdateCalendarParams{
		ID:        models.NewRecordID("calendar", id),
		UserID:    models.NewRecordID("user", claim.Subject),
		Name:      input.Name,
		Color:     input.Color,
		IsDefault: input.IsDefault,
	})
}

// DeleteCalendar is the resolver for the deleteCalendar field.
func (r *mutationResolver) DeleteCalendar(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}
	if err := r.store.Calendars.Delete(ctx,
		models.NewRecordID("calendar", id),
		models.NewRecordID("user", claim.Subject),
	); err != nil {
		return false, err
	}
	return true, nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, from *string, to *string, filter *gql_model.EventFilter) ([]*gql_model.Event, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Events.ListForUser(ctx, models.NewRecordID("user", claim.Subject), from, to, filter)
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*gql_model.Event, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Events.Get(ctx,
		models.NewRecordID("event", id),
		models.NewRecordID("user", claim.Subject),
	)
}

// Calendars is the resolver for the calendars field.
func (r *queryResolver) Calendars(ctx context.Context) ([]*gql_model.Calendar, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Calendars.ListForUser(ctx, models.NewRecordID("user", claim.Subject))
}
