package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"strings"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/neoworks/auth/oauth"
	surrealdb "github.com/surrealdb/surrealdb.go"
	"github.com/surrealdb/surrealdb.go/pkg/models"
	"golang.org/x/crypto/bcrypt"
)

// CreateClient is the resolver for the createClient field.
func (r *mutationResolver) CreateClient(ctx context.Context, input gql_model.CreateClientInput) (*gql_model.CreateClientResult, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}

	// Clients are owned by an organization; the caller must be a member of it.
	orgRef := models.NewRecordID("organization", input.OrganizationID)
	if !r.callerIsMember(ctx, claim.Subject, orgRef) {
		return nil, fmt.Errorf("forbidden: caller is not a member of organization %q", input.OrganizationID)
	}

	autoGrant := input.AutoGrantScopes != nil && *input.AutoGrantScopes
	public := input.Public != nil && *input.Public

	// Confidential clients get a server-generated secret (shown once, stored as bcrypt hash).
	// Public clients (PKCE-only) have no secret.
	var secret *string
	var secretHash *string
	if !public {
		raw := make([]byte, 32)
		if _, err := rand.Read(raw); err != nil {
			return nil, fmt.Errorf("generate secret: %w", err)
		}
		s := base64.RawURLEncoding.EncodeToString(raw)
		secret = &s

		hash, err := bcrypt.GenerateFromPassword([]byte(s), bcrypt.DefaultCost)
		if err != nil {
			return nil, fmt.Errorf("hash secret: %w", err)
		}
		h := string(hash)
		secretHash = &h
	}

	// Use the caller-supplied ID as the record key so the client ID and the DB
	// record ID are the same value, avoiding a separate lookup field.
	// secret_hash is option<string>; omit it for public clients so it defaults to
	// NONE rather than a rejected NULL (see CLAUDE.md).
	assignments := []string{
		"organization      = $organization",
		"created_by        = $created_by",
		"redirect_uris     = $redirect_uris",
		"scopes            = $scopes",
		"auto_grant_scopes = $auto_grant_scopes",
		"public            = $public",
	}
	params := map[string]any{
		"id":                input.ID,
		"organization":      orgRef,
		"created_by":        models.NewRecordID("user", claim.Subject),
		"redirect_uris":     input.RedirectUris,
		"scopes":            input.Scopes,
		"auto_grant_scopes": autoGrant,
		"public":            public,
	}
	if secretHash != nil {
		assignments = append(assignments, "secret_hash = $secret_hash")
		params["secret_hash"] = *secretHash
	}
	if input.Name != nil && *input.Name != "" {
		assignments = append(assignments, "name = $name")
		params["name"] = *input.Name
	}

	results, err := surrealdb.Query[[]oauth.Client](ctx, r.store.DB,
		`CREATE type::record("client", $id) SET `+strings.Join(assignments, ", "), params)
	if err != nil {
		return nil, fmt.Errorf("create client: %w", err)
	}

	var client *gql_model.OAuthClient
	for _, qr := range *results {
		if len(qr.Result) > 0 {
			c := qr.Result[0]
			client = oauthClientToGQL(&c)
			break
		}
	}
	if client == nil {
		return nil, fmt.Errorf("create client: no result")
	}

	return &gql_model.CreateClientResult{
		Client: client,
		Secret: secret,
	}, nil
}

// DeleteClient is the resolver for the deleteClient field.
func (r *mutationResolver) DeleteClient(ctx context.Context, id string) (bool, error) {
	if _, err := surrealdb.Query[[]any](ctx, r.store.DB,
		`DELETE type::record("client", $id)`,
		map[string]any{"id": id},
	); err != nil {
		return false, fmt.Errorf("delete client: %w", err)
	}
	return true, nil
}

// Clients is the resolver for the clients field.
func (r *queryResolver) Clients(ctx context.Context, limit *int, offset *int) ([]*gql_model.OAuthClient, error) {
	l := 50
	if limit != nil {
		l = *limit
	}
	o := 0
	if offset != nil {
		o = *offset
	}

	results, err := surrealdb.Query[[]oauth.Client](ctx, r.store.DB,
		"SELECT * FROM client ORDER BY id ASC LIMIT $limit START $offset",
		map[string]any{"limit": l, "offset": o},
	)
	if err != nil {
		return nil, fmt.Errorf("list clients: %w", err)
	}
	for _, qr := range *results {
		out := make([]*gql_model.OAuthClient, len(qr.Result))
		for i := range qr.Result {
			out[i] = oauthClientToGQL(&qr.Result[i])
		}
		return out, nil
	}
	return nil, nil
}

// OauthClient is the resolver for the oauthClient field.
func (r *queryResolver) OauthClient(ctx context.Context, id string) (*gql_model.OAuthClient, error) {
	results, err := surrealdb.Query[[]oauth.Client](ctx, r.store.DB,
		"SELECT * FROM client WHERE id = $id LIMIT 1",
		map[string]any{"id": models.NewRecordID("client", id)},
	)
	if err != nil {
		return nil, fmt.Errorf("get client: %w", err)
	}
	for _, qr := range *results {
		if len(qr.Result) > 0 {
			return oauthClientToGQL(&qr.Result[0]), nil
		}
	}
	return nil, nil
}
