package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/oauth"
	"github.com/neoworks/auth/storage/database"
	surrealdb "github.com/surrealdb/surrealdb.go"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// CreateClientDatabase is the resolver for the createClientDatabase field.
func (r *mutationResolver) CreateClientDatabase(ctx context.Context, clientID string, name string, schemaSource *string) (*gql_model.CreateClientDatabaseResult, error) {
	if !clientDBIdentRegex.MatchString(name) {
		return nil, fmt.Errorf("invalid database name %q: letters, digits, underscore only", name)
	}

	source := ""
	if schemaSource != nil {
		source = *schemaSource
	}
	schema, ddl, err := compileSchemaSource(ctx, source)
	if err != nil {
		return nil, err
	}
	var tables []rewrittenTable
	if schema != nil {
		tables, err = rewriteSchemaInput(schema)
		if err != nil {
			return nil, fmt.Errorf("schema: %w", err)
		}
	}

	clientRef := models.NewRecordID("client", clientID)

	count, err := r.countClientDatabases(ctx, clientRef)
	if err != nil {
		return nil, err
	}
	if count >= maxDatabasesPerClient {
		return nil, fmt.Errorf("limit reached: maximum %d databases per client", maxDatabasesPerClient)
	}

	namespace, dbName, password, err := r.store.ProvisionClientDatabase(ctx, clientID, name)
	if err != nil {
		return nil, err
	}

	var schemaDef any
	if schema != nil {
		schemaDef = schema
	}
	params := map[string]any{
		"client":     clientRef,
		"name":       name,
		"namespace":  namespace,
		"db_name":    dbName,
		"schema_def": schemaDef,
	}
	// The DSL is the canonical artifact; omit when absent so it defaults to NONE.
	schemaSourceClause := ""
	if source != "" {
		schemaSourceClause = ", schema_source = $schema_source"
		params["schema_source"] = source
	}
	results, err := surrealdb.Query[[]oauth.ClientDatabase](ctx, r.store.DB,
		"CREATE client_database SET client = $client, name = $name, namespace = $namespace, db_name = $db_name, schema_def = $schema_def"+schemaSourceClause,
		params,
	)
	if err != nil {
		return nil, fmt.Errorf("record database: %w", err)
	}

	rec := firstResult(results)
	if rec == nil {
		return nil, fmt.Errorf("create client_database: no result")
	}

	if len(ddl) > 0 {
		if err := r.store.ApplyDDLToClientDB(ctx, namespace, dbName, ddl); err != nil {
			return nil, fmt.Errorf("apply schema: %w", err)
		}
	}
	if err := r.recordClientTables(ctx, rec.ID, schema, tables); err != nil {
		return nil, fmt.Errorf("record client tables: %w", err)
	}

	// Client usage is billed to the owning organization, not the client or any user.
	if orgRef := r.clientOrganization(ctx, clientRef); orgRef != nil {
		_ = r.store.CreateProvisioningBillingEvent(ctx, database.ProvisioningBillingEventParams{
			BillingEventParams: database.BillingEventParams{
				BilledTo:     *orgRef,
				SourceClient: &clientRef,
				Units:        1,
				UnitPrice:    0,
				Currency:     "USD",
				Ref:          rec.ID,
			},
			Resource: "database",
		})
	}

	if r.engine != nil {
		r.engine.Invalidate(clientID, name)
	}

	return &gql_model.CreateClientDatabaseResult{
		Database:   clientDBToGQL(rec),
		DbPassword: password,
	}, nil
}

// UpdateClientDatabaseSchema is the resolver for the updateClientDatabaseSchema field.
func (r *mutationResolver) UpdateClientDatabaseSchema(ctx context.Context, clientID string, name string, schemaSource string) (*gql_model.ClientDatabase, error) {
	schema, ddl, err := compileSchemaSource(ctx, schemaSource)
	if err != nil {
		return nil, err
	}
	if schema == nil {
		return nil, Public("schema source is empty")
	}
	tables, err := rewriteSchemaInput(schema)
	if err != nil {
		return nil, fmt.Errorf("schema: %w", err)
	}

	clientRef := models.NewRecordID("client", clientID)
	results, err := surrealdb.Query[[]oauth.ClientDatabase](ctx, r.store.DB, `
		UPDATE client_database SET schema_def = $schema_def, schema_source = $schema_source
		WHERE client = $client AND name = $name AND status != "deleted"
		RETURN AFTER
	`, map[string]any{
		"client":        clientRef,
		"name":          name,
		"schema_def":    schema,
		"schema_source": schemaSource,
	})
	if err != nil {
		return nil, fmt.Errorf("update schema: %w", err)
	}

	rec := firstResult(results)
	if rec == nil {
		return nil, database.ErrNotFound
	}

	if err := r.store.ApplyDDLToClientDB(ctx, rec.Namespace, rec.DbName, ddl); err != nil {
		return nil, fmt.Errorf("apply schema: %w", err)
	}
	if err := r.recordClientTables(ctx, rec.ID, schema, tables); err != nil {
		return nil, fmt.Errorf("record client tables: %w", err)
	}

	if r.engine != nil {
		r.engine.Invalidate(clientID, name)
	}

	return clientDBToGQL(rec), nil
}

// ApplyClientDatabaseMigrations is the resolver for the applyClientDatabaseMigrations field.
func (r *mutationResolver) ApplyClientDatabaseMigrations(ctx context.Context, clientID string, name string, migrations []*gql_model.MigrationInput) (*gql_model.MigrationResult, error) {
	return r.applyMigrations(ctx, clientID, name, migrations)
}

// ClientDatabases is the resolver for the clientDatabases field.
func (r *queryResolver) ClientDatabases(ctx context.Context, clientID string) ([]*gql_model.ClientDatabase, error) {
	clientRef := models.NewRecordID("client", clientID)
	results, err := surrealdb.Query[[]oauth.ClientDatabase](ctx, r.store.DB, `
		SELECT * FROM client_database
		WHERE client = $client AND status != "deleted"
		ORDER BY created_at ASC
	`, map[string]any{"client": clientRef})
	if err != nil {
		return nil, fmt.Errorf("list databases: %w", err)
	}

	for _, qr := range *results {
		out := make([]*gql_model.ClientDatabase, len(qr.Result))
		for i := range qr.Result {
			out[i] = clientDBToGQL(&qr.Result[i])
		}
		return out, nil
	}
	return nil, nil
}
