package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// SendConnectionRequest is the resolver for the sendConnectionRequest field.
func (r *mutationResolver) SendConnectionRequest(ctx context.Context, userID string) (*gql_model.Connection, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	return r.store.Connections.SendRequest(ctx, me, models.NewRecordID("user", userID))
}

// RespondToConnectionRequest is the resolver for the respondToConnectionRequest field.
func (r *mutationResolver) RespondToConnectionRequest(ctx context.Context, userID string, accept bool) (*gql_model.Connection, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	return r.store.Connections.Respond(ctx, me, models.NewRecordID("user", userID), accept)
}

// RemoveConnection is the resolver for the removeConnection field.
func (r *mutationResolver) RemoveConnection(ctx context.Context, userID string) (bool, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return false, errUnauthenticated
	}
	if err := r.store.Connections.Remove(ctx, me, models.NewRecordID("user", userID)); err != nil {
		return false, err
	}
	return true, nil
}

// BlockUser is the resolver for the blockUser field.
func (r *mutationResolver) BlockUser(ctx context.Context, userID string) (*gql_model.Connection, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	return r.store.Connections.Block(ctx, me, models.NewRecordID("user", userID))
}

// UpdateSharingConsent is the resolver for the updateSharingConsent field.
func (r *mutationResolver) UpdateSharingConsent(ctx context.Context, viewerID string, fields []string) (*gql_model.SharingGrant, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	return r.store.Connections.UpsertGrant(ctx, me, models.NewRecordID("user", viewerID), fields)
}

// SetInvitePolicy is the resolver for the setInvitePolicy field.
func (r *mutationResolver) SetInvitePolicy(ctx context.Context, userID string, policy string) (bool, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return false, errUnauthenticated
	}
	if err := r.store.Connections.SetInvitePolicy(ctx, me, models.NewRecordID("user", userID), policy); err != nil {
		return false, err
	}
	return true, nil
}

// MyConnections is the resolver for the myConnections field.
func (r *queryResolver) MyConnections(ctx context.Context, status *string) ([]*gql_model.Connection, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	return r.store.Connections.ListConnections(ctx, me, status)
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, query string, limit *int) ([]*gql_model.UserSearchResult, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	n := 0
	if limit != nil {
		n = *limit
	}
	return r.store.Connections.SearchUsers(ctx, me, query, n)
}

// ConnectionProfile is the resolver for the connectionProfile field.
func (r *queryResolver) ConnectionProfile(ctx context.Context, userID string) (*gql_model.ConnectionProfile, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	return r.store.Connections.ConnectionProfile(ctx, me, models.NewRecordID("user", userID))
}

// MySharingGrants is the resolver for the mySharingGrants field.
func (r *queryResolver) MySharingGrants(ctx context.Context) ([]*gql_model.SharingGrant, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	return r.store.Connections.ListGrants(ctx, me)
}

// MyInvitePolicies is the resolver for the myInvitePolicies field.
func (r *queryResolver) MyInvitePolicies(ctx context.Context) ([]*gql_model.InvitePolicy, error) {
	me, ok := callerUser(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	return r.store.Connections.ListInvitePolicies(ctx, me)
}
