package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/neoworks/auth/gql"
	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/neoworks/auth/storage/database"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// CreateContact is the resolver for the createContact field.
func (r *mutationResolver) CreateContact(ctx context.Context, input gql_model.CreateContactInput) (*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)

	uid := input.UID
	if uid == nil {
		generated := newContactUID()
		uid = &generated
	}
	fields := database.ContactFields{
		UID:           uid,
		Kind:          input.Kind,
		FormattedName: &input.FormattedName,
		Name:          nameIn(input.Name),
		Nicknames:     input.Nicknames,
		Birthday:      input.Birthday,
		Anniversary:   input.Anniversary,
		Gender:        genderIn(input.Gender),
		Emails:        fieldsIn(input.Emails),
		Phones:        fieldsIn(input.Phones),
		Impps:         fieldsIn(input.Impps),
		Languages:     fieldsIn(input.Languages),
		Addresses:     addressesIn(input.Addresses),
		Organizations: orgsIn(input.Organizations),
		Title:         input.Title,
		Role:          input.Role,
		Timezone:      input.Timezone,
		Geo:           geoIn(input.Geo),
		Categories:    input.Categories,
		Notes:         input.Notes,
		Urls:          fieldsIn(input.Urls),
		Source:        input.Source,
		Prodid:        input.Prodid,
		Fburl:         input.Fburl,
		Caluri:        input.Caluri,
		Caladruri:     input.Caladruri,
		Photo:         mediaRef(input.Photo),
		Logo:          mediaRef(input.Logo),
		Sound:         mediaRef(input.Sound),
		Key:           mediaRef(input.Key),
		CustomFields:  customFieldsIn(input.CustomFields),
		Favorite:      input.Favorite,
	}
	return r.store.Contacts.Create(ctx, &database.CreateContactParams{
		UserID: models.NewRecordID("user", claim.Subject),
		Fields: fields,
	})
}

// UpdateContact is the resolver for the updateContact field.
func (r *mutationResolver) UpdateContact(ctx context.Context, id string, parentVersionIds []string, input gql_model.UpdateContactInput) (*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)

	parents := make([]models.RecordID, len(parentVersionIds))
	for i, pid := range parentVersionIds {
		parents[i] = models.NewRecordID("contact_version", pid)
	}
	fields := database.ContactFields{
		Kind:          input.Kind,
		FormattedName: input.FormattedName,
		Name:          nameIn(input.Name),
		Nicknames:     input.Nicknames,
		Birthday:      input.Birthday,
		Anniversary:   input.Anniversary,
		Gender:        genderIn(input.Gender),
		Emails:        fieldsIn(input.Emails),
		Phones:        fieldsIn(input.Phones),
		Impps:         fieldsIn(input.Impps),
		Languages:     fieldsIn(input.Languages),
		Addresses:     addressesIn(input.Addresses),
		Organizations: orgsIn(input.Organizations),
		Title:         input.Title,
		Role:          input.Role,
		Timezone:      input.Timezone,
		Geo:           geoIn(input.Geo),
		Categories:    input.Categories,
		Notes:         input.Notes,
		Urls:          fieldsIn(input.Urls),
		Source:        input.Source,
		Prodid:        input.Prodid,
		Fburl:         input.Fburl,
		Caluri:        input.Caluri,
		Caladruri:     input.Caladruri,
		Photo:         mediaRef(input.Photo),
		Logo:          mediaRef(input.Logo),
		Sound:         mediaRef(input.Sound),
		Key:           mediaRef(input.Key),
		CustomFields:  customFieldsIn(input.CustomFields),
		Favorite:      input.Favorite,
		Archived:      input.Archived,
	}
	return r.store.Contacts.Update(ctx, &database.UpdateContactParams{
		ID:               models.NewRecordID("contact", id),
		UserID:           models.NewRecordID("user", claim.Subject),
		ParentVersionIDs: parents,
		Fields:           fields,
	})
}

// RestoreContactVersion is the resolver for the restoreContactVersion field.
func (r *mutationResolver) RestoreContactVersion(ctx context.Context, id string, versionID string) (*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.RestoreVersion(ctx,
		models.NewRecordID("contact", id),
		models.NewRecordID("contact_version", versionID),
		models.NewRecordID("user", claim.Subject))
}

// TrashContact is the resolver for the trashContact field.
func (r *mutationResolver) TrashContact(ctx context.Context, id string) (*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.Trash(ctx, models.NewRecordID("contact", id), models.NewRecordID("user", claim.Subject))
}

// RestoreContact is the resolver for the restoreContact field.
func (r *mutationResolver) RestoreContact(ctx context.Context, id string) (*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.Restore(ctx, models.NewRecordID("contact", id), models.NewRecordID("user", claim.Subject))
}

// ArchiveContact is the resolver for the archiveContact field.
func (r *mutationResolver) ArchiveContact(ctx context.Context, id string) (*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.Archive(ctx, models.NewRecordID("contact", id), models.NewRecordID("user", claim.Subject))
}

// UnarchiveContact is the resolver for the unarchiveContact field.
func (r *mutationResolver) UnarchiveContact(ctx context.Context, id string) (*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.Unarchive(ctx, models.NewRecordID("contact", id), models.NewRecordID("user", claim.Subject))
}

// SetContactFavorite is the resolver for the setContactFavorite field.
func (r *mutationResolver) SetContactFavorite(ctx context.Context, id string, favorite bool) (*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.SetFavorite(ctx, models.NewRecordID("contact", id), models.NewRecordID("user", claim.Subject), favorite)
}

// DeleteContact is the resolver for the deleteContact field.
func (r *mutationResolver) DeleteContact(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	err := r.store.Contacts.Delete(ctx, models.NewRecordID("contact", id), models.NewRecordID("user", claim.Subject))
	if err != nil {
		return false, err
	}
	return true, nil
}

// RelateContacts is the resolver for the relateContacts field.
func (r *mutationResolver) RelateContacts(ctx context.Context, fromID string, toID string, types []string, pref *int) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.Relate(ctx, models.NewRecordID("user", claim.Subject),
		models.NewRecordID("contact", fromID), models.NewRecordID("contact", toID), types, pref)
}

// UnrelateContacts is the resolver for the unrelateContacts field.
func (r *mutationResolver) UnrelateContacts(ctx context.Context, fromID string, toID string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.Unrelate(ctx, models.NewRecordID("user", claim.Subject),
		models.NewRecordID("contact", fromID), models.NewRecordID("contact", toID))
}

// AddGroupMember is the resolver for the addGroupMember field.
func (r *mutationResolver) AddGroupMember(ctx context.Context, groupID string, memberID string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.AddMember(ctx, models.NewRecordID("user", claim.Subject),
		models.NewRecordID("contact", groupID), models.NewRecordID("contact", memberID))
}

// RemoveGroupMember is the resolver for the removeGroupMember field.
func (r *mutationResolver) RemoveGroupMember(ctx context.Context, groupID string, memberID string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.RemoveMember(ctx, models.NewRecordID("user", claim.Subject),
		models.NewRecordID("contact", groupID), models.NewRecordID("contact", memberID))
}

// Contacts is the resolver for the contacts field.
func (r *queryResolver) Contacts(ctx context.Context, scope *gql_model.ContactScope, favorite *bool, search *string, filter *gql_model.ContactFilter, sort []*gql_model.ContactSort, limit *int, offset *int) ([]*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)

	resolvedScope := gql_model.ContactScopeActive
	if scope != nil {
		resolvedScope = *scope
	}
	l := 200
	if limit != nil {
		l = *limit
	}
	o := 0
	if offset != nil {
		o = *offset
	}
	return r.store.Contacts.List(ctx, models.NewRecordID("user", claim.Subject), resolvedScope, favorite, search, filter, sort, l, o)
}

// ContactCount is the resolver for the contactCount field.
func (r *queryResolver) ContactCount(ctx context.Context, scope *gql_model.ContactScope, favorite *bool, search *string, filter *gql_model.ContactFilter) (int, error) {
	claim := middleware.ClaimFromContext(ctx)

	resolvedScope := gql_model.ContactScopeActive
	if scope != nil {
		resolvedScope = *scope
	}
	return r.store.Contacts.Count(ctx, models.NewRecordID("user", claim.Subject), resolvedScope, favorite, search, filter)
}

// Contact is the resolver for the contact field.
func (r *queryResolver) Contact(ctx context.Context, id string) (*gql_model.Contact, error) {
	claim := middleware.ClaimFromContext(ctx)
	return r.store.Contacts.Get(ctx, models.NewRecordID("contact", id), models.NewRecordID("user", claim.Subject))
}

// ContactHistory is the resolver for the contactHistory field.
func (r *queryResolver) ContactHistory(ctx context.Context, id string, filter *gql_model.ContactVersionFilter) ([]*gql_model.ContactVersion, error) {
	params := &database.ListVersionsParams{ContactID: models.NewRecordID("contact", id)}
	if filter != nil {
		params.FormattedName = filter.FormattedName
		params.Before = filter.Before
	}
	return r.store.Contacts.ListVersions(ctx, params)
}

// Mutation returns gql.MutationResolver implementation.
func (r *Resolver) Mutation() gql.MutationResolver { return &mutationResolver{r} }

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
