package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/neoworks/auth/email"
	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
)

// SendEmail is the resolver for the sendEmail field.
func (r *mutationResolver) SendEmail(ctx context.Context, input gql_model.SendEmailInput) (*gql_model.SendEmailResult, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	if !claimHasScope(claim, "email:write") {
		return nil, Public("forbidden: requires email:write scope")
	}
	if len(input.To) == 0 {
		return nil, fmt.Errorf("at least one recipient is required")
	}

	msg := email.Message{To: input.To, Subject: input.Subject, Text: input.Text}
	if input.HTML != nil {
		msg.HTML = *input.HTML
	}
	if err := r.mailer.Send(ctx, msg); err != nil {
		return nil, err
	}
	return &gql_model.SendEmailResult{Delivered: true}, nil
}
