package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, filter *gql_model.FileFilter, sort []*gql_model.FileSort, limit *int, offset *int) ([]*gql_model.File, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	l, o := filePaging(limit, offset)
	return r.store.ListFileQuery(ctx, models.NewRecordID("user", claim.Subject), false, filter, sort, l, o)
}

// FileCount is the resolver for the fileCount field.
func (r *queryResolver) FileCount(ctx context.Context, filter *gql_model.FileFilter) (int, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return 0, errUnauthenticated
	}
	return r.store.CountFileQuery(ctx, models.NewRecordID("user", claim.Subject), false, filter)
}

// SharedFile is the resolver for the sharedFile field.
func (r *queryResolver) SharedFile(ctx context.Context, filter *gql_model.FileFilter, sort []*gql_model.FileSort, limit *int, offset *int) ([]*gql_model.File, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	l, o := filePaging(limit, offset)
	return r.store.ListFileQuery(ctx, models.NewRecordID("user", claim.Subject), true, filter, sort, l, o)
}

// SharedFileCount is the resolver for the sharedFileCount field.
func (r *queryResolver) SharedFileCount(ctx context.Context, filter *gql_model.FileFilter) (int, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return 0, errUnauthenticated
	}
	return r.store.CountFileQuery(ctx, models.NewRecordID("user", claim.Subject), true, filter)
}

// FileSearch is the resolver for the fileSearch field.
func (r *queryResolver) FileSearch(ctx context.Context, query string, limit *int, queryVector []float64) ([]*gql_model.File, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	lim := 20
	if limit != nil {
		lim = *limit
	}

	// Server-embed the query text or accept the browser's vector, per the user's
	// search_embedding_mode. A nil vector leaves only the filename BM25 arm.
	queryVec := r.resolveQueryVector(ctx, claim, query, queryVector)
	return r.store.SearchFile(ctx, models.NewRecordID("user", claim.Subject), queryVec, query, lim)
}
