package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// Media is the resolver for the media field.
func (r *queryResolver) Media(ctx context.Context, filter *gql_model.MediaFilter, sort []*gql_model.MediaSort, limit *int, offset *int) ([]*gql_model.Media, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	l, o := mediaPaging(limit, offset)
	return r.store.ListMediaQuery(ctx, models.NewRecordID("user", claim.Subject), false, filter, sort, l, o)
}

// MediaCount is the resolver for the mediaCount field.
func (r *queryResolver) MediaCount(ctx context.Context, filter *gql_model.MediaFilter) (int, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return 0, errUnauthenticated
	}
	return r.store.CountMediaQuery(ctx, models.NewRecordID("user", claim.Subject), false, filter)
}

// SharedMedia is the resolver for the sharedMedia field.
func (r *queryResolver) SharedMedia(ctx context.Context, filter *gql_model.MediaFilter, sort []*gql_model.MediaSort, limit *int, offset *int) ([]*gql_model.Media, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	l, o := mediaPaging(limit, offset)
	return r.store.ListMediaQuery(ctx, models.NewRecordID("user", claim.Subject), true, filter, sort, l, o)
}

// SharedMediaCount is the resolver for the sharedMediaCount field.
func (r *queryResolver) SharedMediaCount(ctx context.Context, filter *gql_model.MediaFilter) (int, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return 0, errUnauthenticated
	}
	return r.store.CountMediaQuery(ctx, models.NewRecordID("user", claim.Subject), true, filter)
}

// MediaSearch is the resolver for the mediaSearch field.
func (r *queryResolver) MediaSearch(ctx context.Context, query string, limit *int, queryVector []float64) ([]*gql_model.Media, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	lim := 20
	if limit != nil {
		lim = *limit
	}

	// Server-embed the query text or accept the browser's vector, per the user's
	// search_embedding_mode. A nil vector leaves only the filename BM25 arm.
	queryVec := r.resolveQueryVector(ctx, claim, query, queryVector)
	return r.store.SearchMedia(ctx, models.NewRecordID("user", claim.Subject), queryVec, query, lim)
}
