package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"strings"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/neoworks/auth/storage/database"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// CreateMemory is the resolver for the createMemory field.
func (r *mutationResolver) CreateMemory(ctx context.Context, input gql_model.CreateMemoryInput) (*gql_model.Memory, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	userID := models.NewRecordID("user", claim.Subject)

	orgID, err := r.memoryOrg(ctx, claim.Subject, input.OrganizationID)
	if err != nil {
		return nil, err
	}

	searchable := false
	if input.Searchable != nil {
		searchable = *input.Searchable
	}
	fields := database.MemoryFields{
		Kind:       input.Kind,
		Title:      input.Title,
		SourceText: input.SourceText,
		Searchable: &searchable,
	}
	if input.Media != nil {
		media := models.NewRecordID("media", *input.Media)
		fields.Media = &media
	}

	memory, err := r.store.Memories.Create(ctx, &database.CreateMemoryParams{
		UserID: userID,
		OrgID:  orgID,
		Fields: fields,
	})
	if err != nil {
		return nil, err
	}

	if searchable && input.SourceText != nil && strings.TrimSpace(*input.SourceText) != "" {
		if err := r.reindexMemory(ctx, models.NewRecordID("memory", memory.ID), userID, *input.SourceText); err != nil {
			return nil, err
		}
	}
	return memory, nil
}

// UpdateMemory is the resolver for the updateMemory field.
func (r *mutationResolver) UpdateMemory(ctx context.Context, id string, input gql_model.UpdateMemoryInput) (*gql_model.Memory, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	userID := models.NewRecordID("user", claim.Subject)
	memoryID := models.NewRecordID("memory", id)

	memory, err := r.store.Memories.Update(ctx, &database.UpdateMemoryParams{
		ID:     memoryID,
		UserID: userID,
		Fields: database.MemoryFields{Title: input.Title, SourceText: input.SourceText},
	})
	if err != nil {
		return nil, err
	}

	// Re-chunk and re-embed when the source text changed on a searchable memory.
	if input.SourceText != nil && memory.Searchable {
		if err := r.reindexMemory(ctx, memoryID, userID, *input.SourceText); err != nil {
			return nil, err
		}
	}
	return memory, nil
}

// DeleteMemory is the resolver for the deleteMemory field.
func (r *mutationResolver) DeleteMemory(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}
	if err := r.store.Memories.Delete(ctx,
		models.NewRecordID("memory", id),
		models.NewRecordID("user", claim.Subject),
	); err != nil {
		return false, err
	}
	return true, nil
}

// SetMemorySearchable is the resolver for the setMemorySearchable field.
func (r *mutationResolver) SetMemorySearchable(ctx context.Context, id string, searchable bool) (*gql_model.Memory, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	userID := models.NewRecordID("user", claim.Subject)
	memoryID := models.NewRecordID("memory", id)

	if !searchable {
		return r.store.Memories.ClearSearchable(ctx, memoryID, userID)
	}

	// Turning indexing on requires plaintext to index. Binary / encrypted-only
	// memories must supply source text via updateMemory first.
	memory, err := r.store.Memories.Get(ctx, memoryID, userID)
	if err != nil {
		return nil, err
	}
	if memory.SourceText == nil || strings.TrimSpace(*memory.SourceText) == "" {
		return nil, Public("cannot index a memory without source text")
	}

	on := true
	updated, err := r.store.Memories.Update(ctx, &database.UpdateMemoryParams{
		ID:     memoryID,
		UserID: userID,
		Fields: database.MemoryFields{Searchable: &on},
	})
	if err != nil {
		return nil, err
	}
	if err := r.reindexMemory(ctx, memoryID, userID, *memory.SourceText); err != nil {
		return nil, err
	}
	return updated, nil
}

// Memories is the resolver for the memories field.
func (r *queryResolver) Memories(ctx context.Context, filter *gql_model.MemoryFilter, sort []*gql_model.MemorySort, limit *int, offset *int) ([]*gql_model.Memory, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	lim, off := 200, 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}
	return r.store.Memories.List(ctx, models.NewRecordID("user", claim.Subject), filter, sort, lim, off)
}

// MemoryCount is the resolver for the memoryCount field.
func (r *queryResolver) MemoryCount(ctx context.Context, filter *gql_model.MemoryFilter) (int, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return 0, errUnauthenticated
	}
	return r.store.Memories.Count(ctx, models.NewRecordID("user", claim.Subject), filter)
}

// Memory is the resolver for the memory field.
func (r *queryResolver) Memory(ctx context.Context, id string) (*gql_model.Memory, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	memory, err := r.store.Memories.Get(ctx,
		models.NewRecordID("memory", id),
		models.NewRecordID("user", claim.Subject),
	)
	if errors.Is(err, database.ErrNotFound) {
		return nil, nil
	}
	return memory, err
}

// SearchMemories is the resolver for the searchMemories field.
func (r *queryResolver) SearchMemories(ctx context.Context, query string, limit *int, queryVector []float64) ([]*gql_model.MemorySearchHit, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	lim := 20
	if limit != nil {
		lim = *limit
	}

	// Server-embed the query text or accept the browser's vector, per the user's
	// search_embedding_mode. A nil vector leaves only the BM25 arm.
	queryVec := r.resolveQueryVector(ctx, claim, query, queryVector)
	return r.store.Memories.SearchMemories(ctx, models.NewRecordID("user", claim.Subject), queryVec, query, lim)
}
