package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	surrealdb "github.com/surrealdb/surrealdb.go"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// SendNotification is the resolver for the sendNotification field.
func (r *mutationResolver) SendNotification(ctx context.Context, input gql_model.SendNotificationInput) (*gql_model.Notification, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	if !claimHasScope(claim, "notification:write") {
		return nil, fmt.Errorf("forbidden: requires notification:write scope")
	}

	// An omitted userId targets the calling user.
	targetUser := claim.Subject
	if input.UserID != nil && *input.UserID != "" {
		targetUser = *input.UserID
	}

	notification, err := r.notify(ctx, targetUser, input.Title, input.Body, input.URL)
	if err != nil {
		return nil, err
	}
	return notificationToGQL(notification), nil
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}
	if _, err := surrealdb.Query[[]dbNotification](ctx, r.store.DB,
		"UPDATE $notification SET read = true WHERE user = $user RETURN AFTER",
		map[string]any{
			"notification": models.NewRecordID("notification", id),
			"user":         models.NewRecordID("user", claim.Subject),
		},
	); err != nil {
		return false, fmt.Errorf("mark notification read: %w", err)
	}
	return true, nil
}

// MyNotifications is the resolver for the myNotifications field.
func (r *queryResolver) MyNotifications(ctx context.Context) ([]*gql_model.Notification, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	results, err := surrealdb.Query[[]dbNotification](ctx, r.store.DB,
		"SELECT * FROM notification WHERE user = $user ORDER BY created_at DESC",
		map[string]any{"user": models.NewRecordID("user", claim.Subject)},
	)
	if err != nil {
		return nil, fmt.Errorf("list notifications: %w", err)
	}
	var out []*gql_model.Notification
	for _, qr := range *results {
		for i := range qr.Result {
			out = append(out, notificationToGQL(&qr.Result[i]))
		}
	}
	return out, nil
}
