package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strings"
	"time"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	surrealdb "github.com/surrealdb/surrealdb.go"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, input gql_model.CreateOrganizationInput) (*gql_model.Organization, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	userRef := models.NewRecordID("user", claim.Subject)

	// Reject duplicate names (case-insensitive) among active organizations.
	taken, err := surrealdb.Query[[]dbOrganization](ctx, r.store.DB,
		"SELECT * FROM organization WHERE string::lowercase(name) = string::lowercase($name) AND deleted_at = NONE LIMIT 1",
		map[string]any{"name": input.Name})
	if err != nil {
		return nil, fmt.Errorf("check organization name: %w", err)
	}
	if firstOrganization(taken) != nil {
		return nil, Public("an organization with this name already exists")
	}

	results, err := surrealdb.Query[[]dbOrganization](ctx, r.store.DB,
		"CREATE organization SET name = $name, slug = $slug, description = $description, billing_email = $billing_email RETURN AFTER",
		map[string]any{
			"name":          input.Name,
			"slug":          input.Slug,
			"description":   input.Description,
			"billing_email": input.BillingEmail,
		})
	if err != nil {
		return nil, fmt.Errorf("create organization: %w", err)
	}
	org := firstOrganization(results)
	if org == nil || org.ID == nil {
		return nil, fmt.Errorf("create organization: no result")
	}

	// The creator becomes the organization's owner.
	if _, err := surrealdb.Query[[]any](ctx, r.store.DB,
		"RELATE $user->membership->$org SET role = \"owner\"",
		map[string]any{"user": userRef, "org": *org.ID},
	); err != nil {
		return nil, fmt.Errorf("create owner membership: %w", err)
	}
	return organizationToGQL(org), nil
}

// UpdateOrganization is the resolver for the updateOrganization field.
func (r *mutationResolver) UpdateOrganization(ctx context.Context, id string, input gql_model.UpdateOrganizationInput) (*gql_model.Organization, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	orgRef := models.NewRecordID("organization", id)
	if !r.callerCanAdminOrg(ctx, claim.Subject, orgRef) {
		return nil, Public("forbidden: caller cannot update organization")
	}

	// Each field is patched only when supplied; unset fields keep their current value.
	results, err := surrealdb.Query[[]dbOrganization](ctx, r.store.DB, `
		UPDATE $org SET
			name          = $name          ?? name,
			description   = $description   ?? description,
			logo_url      = $logo_url      ?? logo_url,
			billing_email = $billing_email ?? billing_email
		WHERE deleted_at = NONE
		RETURN AFTER
	`, map[string]any{
		"org":           orgRef,
		"name":          input.Name,
		"description":   input.Description,
		"logo_url":      input.LogoURL,
		"billing_email": input.BillingEmail,
	})
	if err != nil {
		return nil, fmt.Errorf("update organization: %w", err)
	}
	org := firstOrganization(results)
	if org == nil {
		return nil, Public("organization not found")
	}
	return organizationToGQL(org), nil
}

// AddOrganizationMember is the resolver for the addOrganizationMember field.
func (r *mutationResolver) AddOrganizationMember(ctx context.Context, organizationID string, userID string, role string) (*gql_model.OrganizationMember, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	orgRef := models.NewRecordID("organization", organizationID)
	if !r.callerCanAdminOrg(ctx, claim.Subject, orgRef) {
		return nil, Public("forbidden: caller cannot manage organization members")
	}
	if role != "owner" && role != "admin" && role != "member" && role != "billing" {
		return nil, Public(fmt.Sprintf("invalid role %q", role))
	}

	memberRef := models.NewRecordID("user", userID)
	if _, err := surrealdb.Query[[]any](ctx, r.store.DB,
		"RELATE $user->membership->$org SET role = $role",
		map[string]any{"user": memberRef, "org": orgRef, "role": role},
	); err != nil {
		return nil, fmt.Errorf("add member: %w", err)
	}
	return &gql_model.OrganizationMember{UserID: userID, Role: role}, nil
}

// RemoveOrganizationMember is the resolver for the removeOrganizationMember field.
func (r *mutationResolver) RemoveOrganizationMember(ctx context.Context, organizationID string, userID string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}
	orgRef := models.NewRecordID("organization", organizationID)
	if !r.callerCanAdminOrg(ctx, claim.Subject, orgRef) {
		return false, Public("forbidden: caller cannot manage organization members")
	}

	if _, err := surrealdb.Query[[]any](ctx, r.store.DB,
		"DELETE membership WHERE in = $user AND out = $org",
		map[string]any{"user": models.NewRecordID("user", userID), "org": orgRef},
	); err != nil {
		return false, fmt.Errorf("remove member: %w", err)
	}
	return true, nil
}

// CreateOrgInvite is the resolver for the createOrgInvite field.
func (r *mutationResolver) CreateOrgInvite(ctx context.Context, organizationID string, email string, role string) (*gql_model.OrgInvite, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	orgRef := models.NewRecordID("organization", organizationID)
	if !r.callerCanAdminOrg(ctx, claim.Subject, orgRef) {
		return nil, Public("forbidden: caller cannot invite to this organization")
	}
	if role != "owner" && role != "admin" && role != "member" && role != "billing" {
		return nil, Public(fmt.Sprintf("invalid role %q", role))
	}

	token, err := newInviteToken()
	if err != nil {
		return nil, fmt.Errorf("create invite token: %w", err)
	}
	expiresAt := time.Now().Add(7 * 24 * time.Hour)

	results, err := surrealdb.Query[[]dbOrgInvite](ctx, r.store.DB, `
		CREATE org_invite SET
			organization = $org,
			email        = $email,
			role         = $role,
			token        = $invite_token,
			invited_by   = $user,
			expires_at   = $expires_at
		RETURN AFTER
	`, map[string]any{
		"org":          orgRef,
		"email":        email,
		"role":         role,
		"invite_token": token,
		"user":         models.NewRecordID("user", claim.Subject),
		"expires_at":   expiresAt,
	})
	if err != nil {
		return nil, fmt.Errorf("create invite: %w", err)
	}
	invite := firstOrgInvite(results)
	if invite == nil {
		return nil, fmt.Errorf("create invite: no result")
	}

	r.sendInviteEmail(ctx, email, token)
	return orgInviteToGQL(invite), nil
}

// RevokeOrgInvite is the resolver for the revokeOrgInvite field.
func (r *mutationResolver) RevokeOrgInvite(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}
	inviteRef := models.NewRecordID("org_invite", id)

	loaded, err := surrealdb.Query[[]dbOrgInvite](ctx, r.store.DB,
		"SELECT * FROM $invite", map[string]any{"invite": inviteRef})
	if err != nil {
		return false, fmt.Errorf("load invite: %w", err)
	}
	invite := firstOrgInvite(loaded)
	if invite == nil || invite.Organization == nil {
		return false, Public("invite not found")
	}
	if !r.callerCanAdminOrg(ctx, claim.Subject, *invite.Organization) {
		return false, Public("forbidden: caller cannot revoke this invite")
	}

	if _, err := surrealdb.Query[[]dbOrgInvite](ctx, r.store.DB,
		"UPDATE $invite SET status = \"revoked\" WHERE status = \"pending\"",
		map[string]any{"invite": inviteRef},
	); err != nil {
		return false, fmt.Errorf("revoke invite: %w", err)
	}
	return true, nil
}

// AcceptOrgInvite is the resolver for the acceptOrgInvite field.
func (r *mutationResolver) AcceptOrgInvite(ctx context.Context, token string) (*gql_model.Organization, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}

	loaded, err := surrealdb.Query[[]dbOrgInvite](ctx, r.store.DB,
		"SELECT * FROM org_invite WHERE token = $token AND status = \"pending\" LIMIT 1",
		map[string]any{"token": token})
	if err != nil {
		return nil, fmt.Errorf("load invite: %w", err)
	}
	invite := firstOrgInvite(loaded)
	if invite == nil || invite.Organization == nil {
		return nil, Public("invite not found or already used")
	}
	if time.Now().After(invite.ExpiresAt) {
		return nil, Public("invite has expired")
	}

	// The invite is addressed to a specific email; only that account may accept.
	if !strings.EqualFold(userEmail(ctx, r.store.DB, claim.Subject), invite.Email) {
		return nil, Public("forbidden: invite is addressed to a different email")
	}

	if _, err := surrealdb.Query[[]any](ctx, r.store.DB,
		"RELATE $user->membership->$org SET role = $role",
		map[string]any{
			"user": models.NewRecordID("user", claim.Subject),
			"org":  *invite.Organization,
			"role": invite.Role,
		},
	); err != nil {
		return nil, fmt.Errorf("join organization: %w", err)
	}

	if invite.ID != nil {
		_, _ = surrealdb.Query[[]any](ctx, r.store.DB,
			"UPDATE $invite SET status = \"accepted\"",
			map[string]any{"invite": *invite.ID})
	}

	orgResults, err := surrealdb.Query[[]dbOrganization](ctx, r.store.DB,
		"SELECT * FROM $org WHERE deleted_at = NONE", map[string]any{"org": *invite.Organization})
	if err != nil {
		return nil, fmt.Errorf("load organization: %w", err)
	}
	org := firstOrganization(orgResults)
	if org == nil {
		return nil, Public("organization not found")
	}
	return organizationToGQL(org), nil
}

// MyOrganizations is the resolver for the myOrganizations field.
func (r *queryResolver) MyOrganizations(ctx context.Context) ([]*gql_model.Organization, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	userRef := models.NewRecordID("user", claim.Subject)

	results, err := surrealdb.Query[[]dbOrganization](ctx, r.store.DB, `
		SELECT * FROM organization
		WHERE id INSIDE (SELECT VALUE ->membership->organization FROM $user)[0]
		  AND deleted_at = NONE
		ORDER BY name ASC
	`, map[string]any{"user": userRef})
	if err != nil {
		return nil, fmt.Errorf("list organizations: %w", err)
	}
	return organizationsToGQL(results), nil
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, id string) (*gql_model.Organization, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	orgRef := models.NewRecordID("organization", id)
	if !r.callerIsMember(ctx, claim.Subject, orgRef) {
		return nil, nil
	}

	results, err := surrealdb.Query[[]dbOrganization](ctx, r.store.DB,
		"SELECT * FROM $org WHERE deleted_at = NONE",
		map[string]any{"org": orgRef},
	)
	if err != nil {
		return nil, fmt.Errorf("get organization: %w", err)
	}
	org := firstOrganization(results)
	if org == nil {
		return nil, nil
	}
	return organizationToGQL(org), nil
}

// OrganizationMembers is the resolver for the organizationMembers field.
func (r *queryResolver) OrganizationMembers(ctx context.Context, id string) ([]*gql_model.OrganizationMember, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	orgRef := models.NewRecordID("organization", id)
	if !r.callerIsMember(ctx, claim.Subject, orgRef) {
		return nil, Public("forbidden: caller is not a member of this organization")
	}

	results, err := surrealdb.Query[[]dbMembership](ctx, r.store.DB,
		"SELECT in AS user, role FROM membership WHERE out = $org",
		map[string]any{"org": orgRef},
	)
	if err != nil {
		return nil, fmt.Errorf("list members: %w", err)
	}
	var out []*gql_model.OrganizationMember
	for _, qr := range *results {
		for _, m := range qr.Result {
			userID := ""
			if m.User != nil {
				userID = fmt.Sprintf("%v", m.User.ID)
			}
			out = append(out, &gql_model.OrganizationMember{UserID: userID, Role: m.Role})
		}
	}
	return out, nil
}

// OrganizationInvites is the resolver for the organizationInvites field.
func (r *queryResolver) OrganizationInvites(ctx context.Context, id string) ([]*gql_model.OrgInvite, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	orgRef := models.NewRecordID("organization", id)
	if !r.callerCanAdminOrg(ctx, claim.Subject, orgRef) {
		return nil, Public("forbidden: caller cannot view invites for this organization")
	}

	results, err := surrealdb.Query[[]dbOrgInvite](ctx, r.store.DB,
		"SELECT * FROM org_invite WHERE organization = $org AND status = \"pending\" ORDER BY created_at DESC",
		map[string]any{"org": orgRef},
	)
	if err != nil {
		return nil, fmt.Errorf("list invites: %w", err)
	}
	var out []*gql_model.OrgInvite
	for _, qr := range *results {
		for i := range qr.Result {
			out = append(out, orgInviteToGQL(&qr.Result[i]))
		}
	}
	return out, nil
}
