package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"time"

	"github.com/99designs/gqlgen/graphql"
	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/neoworks/auth/oauth"
	surrealdb "github.com/surrealdb/surrealdb.go"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// RevokeRefreshToken is the resolver for the revokeRefreshToken field.
func (r *mutationResolver) RevokeRefreshToken(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)

	allRead := false
	canRevoke := false
	for _, s := range claim.Scope {
		if s == "tokens:all:read" {
			allRead = true
			canRevoke = true
		}
		if s == "tokens:read" {
			canRevoke = true
		}
	}
	if !canRevoke {
		return false, fmt.Errorf("forbidden: requires tokens:read or tokens:all:read scope")
	}

	if !allRead {
		rt, err := r.store.GetRefreshToken(ctx, id)
		if err != nil {
			return false, fmt.Errorf("refresh token not found")
		}
		if rt.User.ID.(string) != claim.Subject {
			return false, fmt.Errorf("forbidden: token belongs to another user")
		}
	}

	if err := r.store.RevokeRefreshToken(ctx, id); err != nil {
		return false, fmt.Errorf("revoke refresh token: %w", err)
	}
	return true, nil
}

// RefreshTokens is the resolver for the refreshTokens field.
func (r *queryResolver) RefreshTokens(ctx context.Context, limit *int, offset *int) ([]*gql_model.RefreshToken, error) {
	claim := middleware.ClaimFromContext(ctx)

	allRead := false
	clientRead := false
	for _, s := range claim.Scope {
		if s == "tokens:all:read" {
			allRead = true
		}
		if s == "tokens:read" {
			clientRead = true
		}
	}
	if !allRead && !clientRead {
		return nil, fmt.Errorf("forbidden: requires tokens:read or tokens:all:read scope")
	}

	l := 50
	if limit != nil {
		l = *limit
	}
	o := 0
	if offset != nil {
		o = *offset
	}

	fetchClient := false
	for _, f := range graphql.CollectFieldsCtx(ctx, nil) {
		if f.Name == "client" {
			fetchClient = true
			break
		}
	}

	params := map[string]any{
		"user":   models.NewRecordID("user", claim.Subject),
		"limit":  l,
		"offset": o,
	}

	query := "SELECT * FROM refresh_token WHERE user = $user ORDER BY created_at DESC LIMIT $limit START $offset"
	if !allRead {
		query = "SELECT * FROM refresh_token WHERE user = $user AND client = $client ORDER BY created_at DESC LIMIT $limit START $offset"
		params["client"] = models.NewRecordID("client", claim.ClientID)
	}
	if fetchClient {
		query += " FETCH client"
	}

	if fetchClient {
		results, err := surrealdb.Query[[]dbRefreshTokenFetched](ctx, r.store.DB, query, params)
		if err != nil {
			return nil, fmt.Errorf("list refresh tokens: %w", err)
		}
		for _, qr := range *results {
			out := make([]*gql_model.RefreshToken, len(qr.Result))
			for i, rt := range qr.Result {
				var gqlClient *gql_model.OAuthClient
				if rt.Client != nil {
					gqlClient = &gql_model.OAuthClient{
						ID:              fmt.Sprintf("%v", rt.Client.ID.ID),
						Scopes:          rt.Client.Scopes,
						RedirectUris:    rt.Client.RedirectURIs,
						Public:          rt.Client.Public,
						AutoGrantScopes: rt.Client.AutoGrantScopes,
					}
				}
				out[i] = &gql_model.RefreshToken{
					ID:        fmt.Sprintf("%v", rt.ID.ID),
					Client:    gqlClient,
					Scopes:    rt.Scopes,
					ExpiresAt: rt.ExpiresAt.Format(time.RFC3339),
					CreatedAt: rt.CreatedAt.Format(time.RFC3339),
					Revoked:   rt.Revoked,
					Used:      rt.Used,
				}
			}
			return out, nil
		}
	} else {
		results, err := surrealdb.Query[[]oauth.RefreshToken](ctx, r.store.DB, query, params)
		if err != nil {
			return nil, fmt.Errorf("list refresh tokens: %w", err)
		}
		for _, qr := range *results {
			out := make([]*gql_model.RefreshToken, len(qr.Result))
			for i, rt := range qr.Result {
				out[i] = &gql_model.RefreshToken{
					ID:        fmt.Sprintf("%v", rt.ID.ID),
					Client:    &gql_model.OAuthClient{ID: fmt.Sprintf("%v", rt.Client.ID)},
					Scopes:    rt.Scopes,
					ExpiresAt: rt.ExpiresAt.Format(time.RFC3339),
					CreatedAt: rt.CreatedAt.Format(time.RFC3339),
					Revoked:   rt.Revoked,
					Used:      rt.Used,
				}
			}
			return out, nil
		}
	}
	return nil, nil
}
