package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	surrealdb "github.com/surrealdb/surrealdb.go"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// GrantScope is the resolver for the grantScope field.
func (r *mutationResolver) GrantScope(ctx context.Context, clientID string, scope string) (*gql_model.ScopeGrant, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}

	parsed, err := parseScope(scope)
	if err != nil {
		return nil, err
	}

	// An omitted organization segment targets the user's personal data on Neoworks.
	var orgRef *models.RecordID
	if parsed.OrgSlug != "" {
		orgRef, err = r.organizationBySlug(ctx, parsed.OrgSlug)
		if err != nil {
			return nil, err
		}
		if orgRef == nil {
			return nil, fmt.Errorf("unknown organization %q", parsed.OrgSlug)
		}
	}

	userRef := models.NewRecordID("user", claim.Subject)
	clientRef := models.NewRecordID("client", clientID)

	results, err := surrealdb.Query[[]dbScopeGrant](ctx, r.store.DB, `
		CREATE scope_grant SET
			user         = $user,
			client       = $client,
			raw          = $raw,
			organization = $organization,
			entity       = $entity,
			action       = $action
		RETURN AFTER
	`, map[string]any{
		"user":         userRef,
		"client":       clientRef,
		"raw":          scope,
		"organization": orgRef,
		"entity":       parsed.Entity,
		"action":       parsed.Action,
	})
	if err != nil {
		return nil, fmt.Errorf("grant scope: %w", err)
	}
	grant := firstScopeGrant(results)
	if grant == nil {
		return nil, fmt.Errorf("grant scope: no result")
	}
	return scopeGrantToGQL(grant, parsed.OrgSlug), nil
}

// RevokeScope is the resolver for the revokeScope field.
func (r *mutationResolver) RevokeScope(ctx context.Context, id string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}

	// Only the granting user may revoke their own grant.
	if _, err := surrealdb.Query[[]any](ctx, r.store.DB,
		"DELETE scope_grant WHERE id = $id AND user = $user",
		map[string]any{
			"id":   models.NewRecordID("scope_grant", id),
			"user": models.NewRecordID("user", claim.Subject),
		},
	); err != nil {
		return false, fmt.Errorf("revoke scope: %w", err)
	}
	return true, nil
}

// MyScopeGrants is the resolver for the myScopeGrants field.
func (r *queryResolver) MyScopeGrants(ctx context.Context) ([]*gql_model.ScopeGrant, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}

	results, err := surrealdb.Query[[]dbScopeGrant](ctx, r.store.DB, `
		SELECT *, organization.slug AS organization_slug FROM scope_grant
		WHERE user = $user
		ORDER BY created_at DESC
	`, map[string]any{"user": models.NewRecordID("user", claim.Subject)})
	if err != nil {
		return nil, fmt.Errorf("list scope grants: %w", err)
	}

	var out []*gql_model.ScopeGrant
	for _, qr := range *results {
		for i := range qr.Result {
			g := qr.Result[i]
			slug := ""
			if g.OrganizationSlug != nil {
				slug = *g.OrganizationSlug
			}
			out = append(out, scopeGrantToGQL(&g, slug))
		}
	}
	return out, nil
}

// OrganizationScopeEntities is the resolver for the organizationScopeEntities field.
func (r *queryResolver) OrganizationScopeEntities(ctx context.Context, organizationID string) ([]*gql_model.ScopeEntity, error) {
	return r.loadOrganizationScopeEntities(ctx, organizationID)
}
