package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// SetSetting is the resolver for the setSetting field.
func (r *mutationResolver) SetSetting(ctx context.Context, key string, value string) (*gql_model.Setting, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Settings.Set(ctx, claim.ClientID, models.NewRecordID("user", claim.Subject), key, value)
}

// DeleteSetting is the resolver for the deleteSetting field.
func (r *mutationResolver) DeleteSetting(ctx context.Context, key string) (bool, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return false, errUnauthenticated
	}
	if err := r.store.Settings.Delete(ctx, claim.ClientID, models.NewRecordID("user", claim.Subject), key); err != nil {
		return false, err
	}
	return true, nil
}

// Setting is the resolver for the setting field.
func (r *queryResolver) Setting(ctx context.Context, key string, clientID *string) (*gql_model.Setting, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	client := claim.ClientID
	if clientID != nil && *clientID != "" {
		client = *clientID
	}
	return r.store.Settings.Get(ctx, models.NewRecordID("user", claim.Subject), client, key)
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context, clientID *string) ([]*gql_model.Setting, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	return r.store.Settings.List(ctx, models.NewRecordID("user", claim.Subject), clientID)
}
