package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
)

// StorageUsage is the resolver for the storageUsage field.
func (r *queryResolver) StorageUsage(ctx context.Context) (*gql_model.StorageUsage, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}
	if !claimHasScope(claim, "storage:read") {
		return nil, Public("forbidden: requires storage:read scope")
	}

	usage, err := r.store.StorageUsage(ctx, claim.Subject)
	if err != nil {
		return nil, err
	}
	return storageUsageToModel(usage), nil
}
