package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"time"

	gql_model "github.com/neoworks/auth/gql/model"
	"github.com/neoworks/auth/middleware"
	"github.com/surrealdb/surrealdb.go/pkg/models"
)

// DatabaseUsage is the resolver for the databaseUsage field.
func (r *queryResolver) DatabaseUsage(ctx context.Context, clientID string, name string, sinceMinutes *int) (*gql_model.DatabaseUsage, error) {
	claim := middleware.ClaimFromContext(ctx)
	if claim == nil {
		return nil, errUnauthenticated
	}

	orgRef := r.clientOrganization(ctx, models.NewRecordID("client", clientID))
	if orgRef == nil || !r.callerIsMember(ctx, claim.Subject, *orgRef) {
		return nil, Public("forbidden: not a member of the database's organization")
	}

	minutes := defaultUsageWindowMinutes
	if sinceMinutes != nil && *sinceMinutes > 0 {
		minutes = *sinceMinutes
	}
	since := time.Now().Add(-time.Duration(minutes) * time.Minute)

	report, err := r.store.DatabaseUsage(ctx, clientID, name, since)
	if err != nil {
		return nil, err
	}
	return usageReportToGQL(report), nil
}
