// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql_model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// vCard ADR.
type Address struct {
	Types      []string `json:"types,omitempty"`
	Pref       *int     `json:"pref,omitempty"`
	Label      *string  `json:"label,omitempty"`
	PoBox      *string  `json:"po_box,omitempty"`
	Ext        *string  `json:"ext,omitempty"`
	Street     *string  `json:"street,omitempty"`
	Locality   *string  `json:"locality,omitempty"`
	Region     *string  `json:"region,omitempty"`
	PostalCode *string  `json:"postal_code,omitempty"`
	Country    *string  `json:"country,omitempty"`
}

type AddressInput struct {
	Types      []string `json:"types,omitempty"`
	Pref       *int     `json:"pref,omitempty"`
	Label      *string  `json:"label,omitempty"`
	PoBox      *string  `json:"po_box,omitempty"`
	Ext        *string  `json:"ext,omitempty"`
	Street     *string  `json:"street,omitempty"`
	Locality   *string  `json:"locality,omitempty"`
	Region     *string  `json:"region,omitempty"`
	PostalCode *string  `json:"postal_code,omitempty"`
	Country    *string  `json:"country,omitempty"`
}

type Album struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	// Number of media in the album.
	Count int `json:"count"`
	// Thumbnail media id of the most-recently-added member, or null when empty.
	//   Use it for the album card; null renders a placeholder cover.
	CoverThumbnailID *string `json:"coverThumbnailId,omitempty"`
}

type BoolFilter struct {
	Eq *bool `json:"eq,omitempty"`
}

type Calendar struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// One of: green red amber blue violet pink neutral.
	Color     string `json:"color"`
	IsDefault bool   `json:"is_default"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ClientDatabase struct {
	ID        string `json:"id"`
	ClientID  string `json:"client_id"`
	Name      string `json:"name"`
	DbName    string `json:"db_name"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// A connection edge as seen by the caller.
type Connection struct {
	// The other user in the connection (never the caller).
	User   *ConnectionProfile `json:"user"`
	Status string             `json:"status"`
	// Relative to the caller: "outgoing" (caller requested) or "incoming".
	Direction string `json:"direction"`
	CreatedAt string `json:"created_at"`
}

// A user profile projected to only the fields the caller may see. Name is always
// visible between accepted connections; email/avatar_url are null unless a sharing
// grant permits them.
type ConnectionProfile struct {
	ID        string  `json:"id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Email     *string `json:"email,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
}

type Contact struct {
	ID string `json:"id"`
	// vCard UID — stable across imports/sync.
	UID string `json:"uid"`
	// vCard KIND: individual | group | org | location.
	Kind string `json:"kind"`
	// vCard FN — the display name (required).
	FormattedName string                 `json:"formatted_name"`
	Name          *Name                  `json:"name,omitempty"`
	Nicknames     []string               `json:"nicknames,omitempty"`
	Birthday      *string                `json:"birthday,omitempty"`
	Anniversary   *string                `json:"anniversary,omitempty"`
	Gender        *Gender                `json:"gender,omitempty"`
	Emails        []*ContactField        `json:"emails,omitempty"`
	Phones        []*ContactField        `json:"phones,omitempty"`
	Impps         []*ContactField        `json:"impps,omitempty"`
	Languages     []*ContactField        `json:"languages,omitempty"`
	Addresses     []*Address             `json:"addresses,omitempty"`
	Organizations []*ContactOrganization `json:"organizations,omitempty"`
	Title         *string                `json:"title,omitempty"`
	Role          *string                `json:"role,omitempty"`
	Timezone      *string                `json:"timezone,omitempty"`
	Geo           *Geo                   `json:"geo,omitempty"`
	Categories    []string               `json:"categories,omitempty"`
	Notes         []string               `json:"notes,omitempty"`
	Urls          []*ContactField        `json:"urls,omitempty"`
	Source        *string                `json:"source,omitempty"`
	Prodid        *string                `json:"prodid,omitempty"`
	Fburl         *string                `json:"fburl,omitempty"`
	Caluri        *string                `json:"caluri,omitempty"`
	Caladruri     *string                `json:"caladruri,omitempty"`
	// Media handler id for the encrypted PHOTO/LOGO/SOUND/KEY (null = none).
	Photo        *string        `json:"photo,omitempty"`
	Logo         *string        `json:"logo,omitempty"`
	Sound        *string        `json:"sound,omitempty"`
	Key          *string        `json:"key,omitempty"`
	CustomFields []*CustomField `json:"custom_fields,omitempty"`
	Favorite     bool           `json:"favorite"`
	Archived     bool           `json:"archived"`
	Deleted      bool           `json:"deleted"`
	// vCard RELATED edges and KIND=group MEMBER ids, from the graph.
	Related   []*ContactRelation `json:"related,omitempty"`
	MemberIds []string           `json:"member_ids,omitempty"`
	CreatedAt string             `json:"created_at"`
	UpdatedAt string             `json:"updated_at"`
}

// A typed, repeatable value (EMAIL, TEL, IMPP, URL, LANG). `types` carries the
// vCard TYPE parameter (home, work, cell, …); `pref` the PREF (1 = most preferred).
type ContactField struct {
	Value string   `json:"value"`
	Types []string `json:"types,omitempty"`
	Pref  *int     `json:"pref,omitempty"`
	Label *string  `json:"label,omitempty"`
}

// Match a single element of a repeatable field (email/phone): value substring/eq
// and an optional membership test on its types.
type ContactFieldFilter struct {
	Value *StringFilter `json:"value,omitempty"`
	Type  *string       `json:"type,omitempty"`
}

type ContactFieldInput struct {
	Value string   `json:"value"`
	Types []string `json:"types,omitempty"`
	Pref  *int     `json:"pref,omitempty"`
	Label *string  `json:"label,omitempty"`
}

type ContactFilter struct {
	FormattedName *StringFilter     `json:"formatted_name,omitempty"`
	Kind          *StringFilter     `json:"kind,omitempty"`
	Birthday      *StringFilter     `json:"birthday,omitempty"`
	Anniversary   *StringFilter     `json:"anniversary,omitempty"`
	Title         *StringFilter     `json:"title,omitempty"`
	Role          *StringFilter     `json:"role,omitempty"`
	Timezone      *StringFilter     `json:"timezone,omitempty"`
	Geo           *GeoFilter        `json:"geo,omitempty"`
	Emails        *FieldListFilter  `json:"emails,omitempty"`
	Phones        *FieldListFilter  `json:"phones,omitempty"`
	Impps         *FieldListFilter  `json:"impps,omitempty"`
	Languages     *FieldListFilter  `json:"languages,omitempty"`
	Urls          *FieldListFilter  `json:"urls,omitempty"`
	Categories    *StringListFilter `json:"categories,omitempty"`
	Nicknames     *StringListFilter `json:"nicknames,omitempty"`
	Notes         *StringListFilter `json:"notes,omitempty"`
	Favorite      *BoolFilter       `json:"favorite,omitempty"`
	Archived      *BoolFilter       `json:"archived,omitempty"`
	Deleted       *BoolFilter       `json:"deleted,omitempty"`
	CreatedAt     *DateFilter       `json:"created_at,omitempty"`
	UpdatedAt     *DateFilter       `json:"updated_at,omitempty"`
	And           []*ContactFilter  `json:"and,omitempty"`
	Or            []*ContactFilter  `json:"or,omitempty"`
	Not           *ContactFilter    `json:"not,omitempty"`
}

// vCard ORG (name plus organisational units).
type ContactOrganization struct {
	Name  string   `json:"name"`
	Units []string `json:"units,omitempty"`
}

type ContactOrganizationInput struct {
	Name  string   `json:"name"`
	Units []string `json:"units,omitempty"`
}

// A vCard RELATED edge to another contact.
type ContactRelation struct {
	ContactID string   `json:"contact_id"`
	Types     []string `json:"types,omitempty"`
	Pref      *int     `json:"pref,omitempty"`
}

// One sort key. Pass a list to sort by several columns in order.
type ContactSort struct {
	Field     ContactSortField `json:"field"`
	Direction *SortDirection   `json:"direction,omitempty"`
}

// A point-in-time snapshot from the append-only history. Mirrors Contact's data
// fields (graph relations are not versioned).
type ContactVersion struct {
	ID            string                 `json:"id"`
	ContactID     string                 `json:"contact_id"`
	UID           string                 `json:"uid"`
	Kind          string                 `json:"kind"`
	FormattedName string                 `json:"formatted_name"`
	Name          *Name                  `json:"name,omitempty"`
	Nicknames     []string               `json:"nicknames,omitempty"`
	Birthday      *string                `json:"birthday,omitempty"`
	Anniversary   *string                `json:"anniversary,omitempty"`
	Gender        *Gender                `json:"gender,omitempty"`
	Emails        []*ContactField        `json:"emails,omitempty"`
	Phones        []*ContactField        `json:"phones,omitempty"`
	Impps         []*ContactField        `json:"impps,omitempty"`
	Languages     []*ContactField        `json:"languages,omitempty"`
	Addresses     []*Address             `json:"addresses,omitempty"`
	Organizations []*ContactOrganization `json:"organizations,omitempty"`
	Title         *string                `json:"title,omitempty"`
	Role          *string                `json:"role,omitempty"`
	Timezone      *string                `json:"timezone,omitempty"`
	Geo           *Geo                   `json:"geo,omitempty"`
	Categories    []string               `json:"categories,omitempty"`
	Notes         []string               `json:"notes,omitempty"`
	Urls          []*ContactField        `json:"urls,omitempty"`
	Source        *string                `json:"source,omitempty"`
	Prodid        *string                `json:"prodid,omitempty"`
	Fburl         *string                `json:"fburl,omitempty"`
	Caluri        *string                `json:"caluri,omitempty"`
	Caladruri     *string                `json:"caladruri,omitempty"`
	Photo         *string                `json:"photo,omitempty"`
	Logo          *string                `json:"logo,omitempty"`
	Sound         *string                `json:"sound,omitempty"`
	Key           *string                `json:"key,omitempty"`
	CustomFields  []*CustomField         `json:"custom_fields,omitempty"`
	Favorite      bool                   `json:"favorite"`
	Archived      bool                   `json:"archived"`
	Deleted       bool                   `json:"deleted"`
	CreatedAt     string                 `json:"created_at"`
	// Version ids this one derives from (edit lineage; 2 entries on a merge).
	ParentIds []string `json:"parent_ids,omitempty"`
}

type ContactVersionFilter struct {
	FormattedName *string `json:"formatted_name,omitempty"`
	Before        *string `json:"before,omitempty"`
}

type CreateCalendarInput struct {
	Name      string `json:"name"`
	Color     string `json:"color"`
	IsDefault *bool  `json:"is_default,omitempty"`
}

// Returned once on creation. db_password is shown only once — store it securely.
type CreateClientDatabaseResult struct {
	Database   *ClientDatabase `json:"database"`
	DbPassword string          `json:"db_password"`
}

type CreateClientInput struct {
	// Used as both the OAuth client_id and the SurrealDB record key.
	// Must be unique across all clients (e.g. "myapp.example.com").
	ID string `json:"id"`
	// The organization that will own this client. The caller must be a member of it.
	OrganizationID string `json:"organizationId"`
	// Human-readable display name shown in first-party UI (e.g. the Vault).
	Name         *string  `json:"name,omitempty"`
	RedirectUris []string `json:"redirect_uris"`
	// Scopes this client is allowed to request.
	Scopes []string `json:"scopes"`
	// When true, the consent screen is skipped and scopes are granted automatically.
	// Intended for first-party apps where the user owns both the app and the resource.
	AutoGrantScopes *bool `json:"auto_grant_scopes,omitempty"`
	// When true, no secret is generated. The client authenticates via PKCE only.
	// Suitable for SPAs and native apps that cannot safely store a secret.
	Public *bool `json:"public,omitempty"`
}

// Returned once on creation. secret is null for public (PKCE-only) clients.
type CreateClientResult struct {
	Client *OAuthClient `json:"client"`
	// null for public clients
	Secret *string `json:"secret,omitempty"`
}

// Create a contact. Only formatted_name is required; kind defaults to individual.
// A uid is generated when omitted.
type CreateContactInput struct {
	UID           *string                     `json:"uid,omitempty"`
	Kind          *string                     `json:"kind,omitempty"`
	FormattedName string                      `json:"formatted_name"`
	Name          *NameInput                  `json:"name,omitempty"`
	Nicknames     []string                    `json:"nicknames,omitempty"`
	Birthday      *string                     `json:"birthday,omitempty"`
	Anniversary   *string                     `json:"anniversary,omitempty"`
	Gender        *GenderInput                `json:"gender,omitempty"`
	Emails        []*ContactFieldInput        `json:"emails,omitempty"`
	Phones        []*ContactFieldInput        `json:"phones,omitempty"`
	Impps         []*ContactFieldInput        `json:"impps,omitempty"`
	Languages     []*ContactFieldInput        `json:"languages,omitempty"`
	Addresses     []*AddressInput             `json:"addresses,omitempty"`
	Organizations []*ContactOrganizationInput `json:"organizations,omitempty"`
	Title         *string                     `json:"title,omitempty"`
	Role          *string                     `json:"role,omitempty"`
	Timezone      *string                     `json:"timezone,omitempty"`
	Geo           *GeoInput                   `json:"geo,omitempty"`
	Categories    []string                    `json:"categories,omitempty"`
	Notes         []string                    `json:"notes,omitempty"`
	Urls          []*ContactFieldInput        `json:"urls,omitempty"`
	Source        *string                     `json:"source,omitempty"`
	Prodid        *string                     `json:"prodid,omitempty"`
	Fburl         *string                     `json:"fburl,omitempty"`
	Caluri        *string                     `json:"caluri,omitempty"`
	Caladruri     *string                     `json:"caladruri,omitempty"`
	Photo         *string                     `json:"photo,omitempty"`
	Logo          *string                     `json:"logo,omitempty"`
	Sound         *string                     `json:"sound,omitempty"`
	Key           *string                     `json:"key,omitempty"`
	CustomFields  []*CustomFieldInput         `json:"custom_fields,omitempty"`
	Favorite      *bool                       `json:"favorite,omitempty"`
}

type CreateEventInput struct {
	CalendarID              *string                `json:"calendarId,omitempty"`
	Title                   string                 `json:"title"`
	Description             *string                `json:"description,omitempty"`
	Start                   string                 `json:"start"`
	Duration                *string                `json:"duration,omitempty"`
	TimeZone                *string                `json:"time_zone,omitempty"`
	ShowWithoutTime         *bool                  `json:"show_without_time,omitempty"`
	Status                  *string                `json:"status,omitempty"`
	FreeBusyStatus          *string                `json:"free_busy_status,omitempty"`
	Privacy                 *string                `json:"privacy,omitempty"`
	Priority                *int                   `json:"priority,omitempty"`
	Color                   *string                `json:"color,omitempty"`
	Keywords                []string               `json:"keywords,omitempty"`
	Participants            map[string]any         `json:"participants,omitempty"`
	Locations               map[string]any         `json:"locations,omitempty"`
	VirtualLocations        map[string]any         `json:"virtual_locations,omitempty"`
	Alerts                  map[string]any         `json:"alerts,omitempty"`
	Links                   map[string]any         `json:"links,omitempty"`
	RelatedTo               map[string]any         `json:"related_to,omitempty"`
	Localizations           map[string]any         `json:"localizations,omitempty"`
	RecurrenceOverrides     map[string]any         `json:"recurrence_overrides,omitempty"`
	RecurrenceRules         []*RecurrenceRuleInput `json:"recurrence_rules,omitempty"`
	ExcludedRecurrenceRules []*RecurrenceRuleInput `json:"excluded_recurrence_rules,omitempty"`
}

// Create a memory. `sourceText` is required for searchable text memories; binary
// kinds reference encrypted bytes via `media`. `searchable` defaults to false on
// multi-tenant deployments (forced true on self-host).
type CreateMemoryInput struct {
	Kind           *string `json:"kind,omitempty"`
	Title          *string `json:"title,omitempty"`
	SourceText     *string `json:"sourceText,omitempty"`
	Media          *string `json:"media,omitempty"`
	Searchable     *bool   `json:"searchable,omitempty"`
	OrganizationID *string `json:"organizationId,omitempty"`
}

type CreateOrganizationInput struct {
	Name string `json:"name"`
	// Used as the organization token in scopes (e.g. "org_123"). Must be unique.
	Slug         string  `json:"slug"`
	Description  *string `json:"description,omitempty"`
	BillingEmail *string `json:"billing_email,omitempty"`
}

// A labelled key/value pair beyond the vCard surface (replaces X- extensions).
type CustomField struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

type CustomFieldInput struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// Internal compiled representation of a client schema. Clients no longer submit this
// directly — they author in the OpenSchema DSL (`schemaSource`), which the server
// compiles into this shape before generating SurrealQL DDL.
type DatabaseSchemaInput struct {
	Tables []*TableDefInput `json:"tables"`
}

type DatabaseUsage struct {
	Current        *DatabaseUsageCurrent `json:"current"`
	InstanceSeries []*UsagePoint         `json:"instanceSeries"`
	QuerySeries    []*QueryUsagePoint    `json:"querySeries"`
}

// Latest snapshot shown as gauges.
type DatabaseUsageCurrent struct {
	CPUPercent        float64 `json:"cpu_percent"`
	MemBytes          float64 `json:"mem_bytes"`
	MemPercent        float64 `json:"mem_percent"`
	StorageBytes      float64 `json:"storage_bytes"`
	AvgLatencyMs      float64 `json:"avg_latency_ms"`
	ActiveConnections int     `json:"active_connections"`
	QueryCount        int     `json:"query_count"`
}

// Operators for a real datetime field (created_at / updated_at / start). String
// values are ISO-8601 instants; `withinLast` is a SurrealDB duration like `30d`.
type DateFilter struct {
	Eq         *string `json:"eq,omitempty"`
	Before     *string `json:"before,omitempty"`
	After      *string `json:"after,omitempty"`
	WithinLast *string `json:"withinLast,omitempty"`
}

type Event struct {
	ID string `json:"id"`
	// The user who owns this event (its creator).
	OwnerID string `json:"owner_id"`
	// The caller's relationship to this event: "owner", or — for an invited
	//   participant — "accepted" | "pending" | "declined". Null if neither.
	MyAttendance *string `json:"my_attendance,omitempty"`
	// Globally-unique jsCalendar identifier (stable across instances).
	UID string `json:"uid"`
	// The calendar this event belongs to; drives its colour. Null = none.
	CalendarID  *string `json:"calendar_id,omitempty"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	// jsCalendar LocalDateTime (no offset), e.g. 2026-06-14T09:00:00.
	Start string `json:"start"`
	// ISO-8601 duration, e.g. PT1H. Absent = instant.
	Duration *string `json:"duration,omitempty"`
	// IANA time zone; null = floating.
	TimeZone                *string           `json:"time_zone,omitempty"`
	ShowWithoutTime         bool              `json:"show_without_time"`
	Status                  *string           `json:"status,omitempty"`
	FreeBusyStatus          *string           `json:"free_busy_status,omitempty"`
	Privacy                 *string           `json:"privacy,omitempty"`
	Priority                *int              `json:"priority,omitempty"`
	Color                   *string           `json:"color,omitempty"`
	Sequence                *int              `json:"sequence,omitempty"`
	Keywords                []string          `json:"keywords,omitempty"`
	Participants            map[string]any    `json:"participants,omitempty"`
	Locations               map[string]any    `json:"locations,omitempty"`
	VirtualLocations        map[string]any    `json:"virtual_locations,omitempty"`
	Alerts                  map[string]any    `json:"alerts,omitempty"`
	Links                   map[string]any    `json:"links,omitempty"`
	RelatedTo               map[string]any    `json:"related_to,omitempty"`
	Localizations           map[string]any    `json:"localizations,omitempty"`
	RecurrenceOverrides     map[string]any    `json:"recurrence_overrides,omitempty"`
	RecurrenceRules         []*RecurrenceRule `json:"recurrence_rules,omitempty"`
	ExcludedRecurrenceRules []*RecurrenceRule `json:"excluded_recurrence_rules,omitempty"`
	CreatedAt               string            `json:"created_at"`
	UpdatedAt               string            `json:"updated_at"`
}

// Structured per-field filter for events, built on the shared operator inputs
// (see _shared.graphql). The `start` operators apply to the resolved start_time.
type EventFilter struct {
	Title          *StringFilter     `json:"title,omitempty"`
	Description    *StringFilter     `json:"description,omitempty"`
	Status         *StringFilter     `json:"status,omitempty"`
	FreeBusyStatus *StringFilter     `json:"free_busy_status,omitempty"`
	Privacy        *StringFilter     `json:"privacy,omitempty"`
	TimeZone       *StringFilter     `json:"time_zone,omitempty"`
	Color          *StringFilter     `json:"color,omitempty"`
	Priority       *IntFilter        `json:"priority,omitempty"`
	Sequence       *IntFilter        `json:"sequence,omitempty"`
	Keywords       *StringListFilter `json:"keywords,omitempty"`
	Start          *DateFilter       `json:"start,omitempty"`
	CreatedAt      *DateFilter       `json:"created_at,omitempty"`
	UpdatedAt      *DateFilter       `json:"updated_at,omitempty"`
	And            []*EventFilter    `json:"and,omitempty"`
	Or             []*EventFilter    `json:"or,omitempty"`
	Not            *EventFilter      `json:"not,omitempty"`
}

type FieldDefInput struct {
	Name string `json:"name"`
	// Allowed base types: string, int, float, decimal, bool, datetime, duration, bytes, uuid, object, any.
	// Parameterized: option<T>, array<T>, set<T> (recursively).
	Type string `json:"type"`
}

// Filter a repeatable field list (emails/phones) by any-element match or size.
type FieldListFilter struct {
	Any     *ContactFieldFilter `json:"any,omitempty"`
	IsEmpty *bool               `json:"isEmpty,omitempty"`
	Size    *IntFilter          `json:"size,omitempty"`
}

// vCard GENDER.
type Gender struct {
	// vCard sex component: M F O N U.
	Sex *string `json:"sex,omitempty"`
	// Free-text gender identity.
	Identity *string `json:"identity,omitempty"`
}

type GenderInput struct {
	Sex      *string `json:"sex,omitempty"`
	Identity *string `json:"identity,omitempty"`
}

// vCard GEO.
type Geo struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

// Geo predicates against a GEO point (lat/lng).
type GeoFilter struct {
	// Within radiusMeters of the given point (haversine, metres).
	Near *NearInput `json:"near,omitempty"`
	// GeoJSON geometry (e.g. a Polygon). The point must fall inside it.
	Within map[string]any `json:"within,omitempty"`
	IsNull *bool          `json:"isNull,omitempty"`
}

type GeoInput struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

// A GPS coordinate (decimal degrees).
type GeoPoint struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type IndexDefInput struct {
	Name   string   `json:"name"`
	Fields []string `json:"fields"`
	Unique *bool    `json:"unique,omitempty"`
	// When true, the index is a FULLTEXT (BM25) index instead of a plain/unique one,
	// enabling the `search` argument on the table's list query. Only valid on string
	// fields. `unique` is ignored for fulltext indexes.
	Fulltext *bool `json:"fulltext,omitempty"`
	// Analyzer for a fulltext index. Defaults to the built-in "text_en".
	Analyzer *string `json:"analyzer,omitempty"`
}

type IntFilter struct {
	Eq *int `json:"eq,omitempty"`
	Gt *int `json:"gt,omitempty"`
	Lt *int `json:"lt,omitempty"`
}

// How the caller handles calendar invites from a specific user.
type InvitePolicy struct {
	// The other user the policy applies to.
	User *ConnectionProfile `json:"user"`
	// "block" | "auto_accept".
	Policy string `json:"policy"`
}

type Media struct {
	ID        string `json:"id"`
	Filename  string `json:"filename"`
	MimeType  string `json:"mime_type"`
	Size      int    `json:"size"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	// The linked thumbnail media id, if one was generated. Load this for grids;
	//   load the original (id) only for fullsize viewing.
	ThumbnailID *string `json:"thumbnailId,omitempty"`
	// Embedding lifecycle for visual/text search: pending | ready | failed | none.
	EmbeddingStatus *string `json:"embeddingStatus,omitempty"`
	// Original capture time from the photo's EXIF (DateTimeOriginal), if present.
	//   Distinct from created_at, which is when the upload reached the server.
	CaptureDate *string `json:"captureDate,omitempty"`
	// GPS coordinate from the photo's EXIF, if present. Stored unencrypted.
	Location *GeoPoint `json:"location,omitempty"`
	// Full parsed EXIF tag set, stored unencrypted. Shape varies by camera.
	Exif map[string]any `json:"exif,omitempty"`
	// True when the caller has favorited this media (per-user, resolved via a
	//   media_favorite subquery — like embeddingStatus).
	Favorite bool `json:"favorite"`
}

type MediaFilter struct {
	Filename    *StringFilter  `json:"filename,omitempty"`
	MimeType    *StringFilter  `json:"mime_type,omitempty"`
	Size        *IntFilter     `json:"size,omitempty"`
	CreatedAt   *DateFilter    `json:"created_at,omitempty"`
	UpdatedAt   *DateFilter    `json:"updated_at,omitempty"`
	CaptureDate *DateFilter    `json:"captureDate,omitempty"`
	Location    *GeoFilter     `json:"location,omitempty"`
	And         []*MediaFilter `json:"and,omitempty"`
	Or          []*MediaFilter `json:"or,omitempty"`
	Not         *MediaFilter   `json:"not,omitempty"`
}

// One sort key. Pass a list to sort by several columns in order.
type MediaSort struct {
	Field     MediaSortField `json:"field"`
	Direction *SortDirection `json:"direction,omitempty"`
}

type Memory struct {
	ID string `json:"id"`
	// Owning organization id, when the memory is shared in an org (null = personal).
	OrganizationID *string `json:"organization_id,omitempty"`
	// text | image | audio | video | document.
	Kind  string  `json:"kind"`
	Title *string `json:"title,omitempty"`
	// Plaintext source — present only when searchable; null otherwise.
	SourceText *string `json:"source_text,omitempty"`
	// Media handler id for encrypted bytes (null = none).
	Media      *string `json:"media,omitempty"`
	Searchable bool    `json:"searchable"`
	Deleted    bool    `json:"deleted"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
}

type MemoryFilter struct {
	Kind       *StringFilter   `json:"kind,omitempty"`
	Title      *StringFilter   `json:"title,omitempty"`
	Searchable *BoolFilter     `json:"searchable,omitempty"`
	Deleted    *BoolFilter     `json:"deleted,omitempty"`
	CreatedAt  *DateFilter     `json:"created_at,omitempty"`
	UpdatedAt  *DateFilter     `json:"updated_at,omitempty"`
	And        []*MemoryFilter `json:"and,omitempty"`
	Or         []*MemoryFilter `json:"or,omitempty"`
	Not        *MemoryFilter   `json:"not,omitempty"`
}

// A memory matched by searchMemories, with its fused relevance score and the
// best-matching chunk text as a snippet.
type MemorySearchHit struct {
	Memory  *Memory `json:"memory"`
	Score   float64 `json:"score"`
	Snippet *string `json:"snippet,omitempty"`
}

type MemorySort struct {
	Field     MemorySortField `json:"field"`
	Direction *SortDirection  `json:"direction,omitempty"`
}

// One ordered migration step for a client database. Apply `schema` (declarative
// DDL, idempotent) and/or `statements` (imperative SurrealQL, e.g. data backfills).
// Each version runs at most once; the server records applied versions per database.
type MigrationInput struct {
	// Monotonic version. Only versions greater than the database's current version run.
	Version int    `json:"version"`
	Name    string `json:"name"`
	// Optional OpenSchema DSL applied at this version (compiled to DDL, idempotent).
	SchemaSource *string `json:"schemaSource,omitempty"`
	// Optional imperative SurrealQL statements (run as admin against this database).
	Statements []string `json:"statements,omitempty"`
}

type MigrationResult struct {
	// Versions applied by this call, in order.
	Applied []int `json:"applied"`
	// The database's version after this call.
	CurrentVersion int `json:"currentVersion"`
}

type Mutation struct {
}

// A jsCalendar NDay: a weekday, optionally restricted to the Nth in the period.
type NDay struct {
	// Weekday code: mo tu we th fr sa su.
	Day         string `json:"day"`
	NthOfPeriod *int   `json:"nthOfPeriod,omitempty"`
}

type NDayInput struct {
	Day         string `json:"day"`
	NthOfPeriod *int   `json:"nthOfPeriod,omitempty"`
}

// vCard N — the structured name.
type Name struct {
	Family     *string  `json:"family,omitempty"`
	Given      *string  `json:"given,omitempty"`
	Additional []string `json:"additional,omitempty"`
	Prefixes   []string `json:"prefixes,omitempty"`
	Suffixes   []string `json:"suffixes,omitempty"`
}

type NameInput struct {
	Family     *string  `json:"family,omitempty"`
	Given      *string  `json:"given,omitempty"`
	Additional []string `json:"additional,omitempty"`
	Prefixes   []string `json:"prefixes,omitempty"`
	Suffixes   []string `json:"suffixes,omitempty"`
}

// A centre point plus radius for proximity search.
type NearInput struct {
	Lat          float64 `json:"lat"`
	Lng          float64 `json:"lng"`
	RadiusMeters float64 `json:"radiusMeters"`
}

type Notification struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Body      string  `json:"body"`
	URL       *string `json:"url,omitempty"`
	Read      bool    `json:"read"`
	CreatedAt string  `json:"created_at"`
}

type OAuthClient struct {
	ID string `json:"id"`
	// Human-readable display name, shown in first-party UI (e.g. the Vault).
	Name *string `json:"name,omitempty"`
	// Scopes this client is allowed to request.
	Scopes       []string `json:"scopes"`
	RedirectUris []string `json:"redirect_uris"`
	// True = PKCE-only; client has no secret.
	Public bool `json:"public"`
	// True = consent screen is skipped; scopes granted automatically.
	AutoGrantScopes bool `json:"auto_grant_scopes"`
}

// An organization's billing / payment-method state.
type OrgBillingStatus struct {
	// One of none, pending, valid, invalid.
	Status string `json:"status"`
	// True once a reusable payment mandate has been captured.
	HasPaymentMethod bool `json:"has_payment_method"`
}

type OrgInvite struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type Organization struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Slug         string  `json:"slug"`
	Description  *string `json:"description,omitempty"`
	LogoURL      *string `json:"logo_url,omitempty"`
	BillingEmail *string `json:"billing_email,omitempty"`
	CreatedAt    string  `json:"created_at"`
}

type OrganizationMember struct {
	UserID string `json:"user_id"`
	// Display name for the member (display name, full name, or email).
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Role  string  `json:"role"`
}

// Result of starting Mollie payment-method setup for an organization.
type PaymentSetup struct {
	// Hosted Mollie checkout the caller must be redirected to.
	CheckoutURL string `json:"checkout_url"`
}

type Query struct {
}

// One per-database query sample at a point in time.
type QueryUsagePoint struct {
	SampledAt         string  `json:"sampled_at"`
	QueryCount        int     `json:"query_count"`
	AvgLatencyMs      float64 `json:"avg_latency_ms"`
	ActiveConnections int     `json:"active_connections"`
}

// A jsCalendar RecurrenceRule (subset).
type RecurrenceRule struct {
	// yearly | monthly | weekly | daily | hourly | minutely | secondly.
	Frequency string `json:"frequency"`
	Interval  *int   `json:"interval,omitempty"`
	// Inclusive end, jsCalendar LocalDateTime.
	Until          *string  `json:"until,omitempty"`
	Count          *int     `json:"count,omitempty"`
	FirstDayOfWeek *string  `json:"firstDayOfWeek,omitempty"`
	ByDay          []*NDay  `json:"byDay,omitempty"`
	ByMonthDay     []int    `json:"byMonthDay,omitempty"`
	ByMonth        []string `json:"byMonth,omitempty"`
	BySetPosition  []int    `json:"bySetPosition,omitempty"`
}

type RecurrenceRuleInput struct {
	Frequency      string       `json:"frequency"`
	Interval       *int         `json:"interval,omitempty"`
	Until          *string      `json:"until,omitempty"`
	Count          *int         `json:"count,omitempty"`
	FirstDayOfWeek *string      `json:"firstDayOfWeek,omitempty"`
	ByDay          []*NDayInput `json:"byDay,omitempty"`
	ByMonthDay     []int        `json:"byMonthDay,omitempty"`
	ByMonth        []string     `json:"byMonth,omitempty"`
	BySetPosition  []int        `json:"bySetPosition,omitempty"`
}

type RefreshToken struct {
	ID        string       `json:"id"`
	Client    *OAuthClient `json:"client"`
	Scopes    []string     `json:"scopes"`
	ExpiresAt string       `json:"expires_at"`
	CreatedAt string       `json:"created_at"`
	Revoked   bool         `json:"revoked"`
	Used      bool         `json:"used"`
}

// A data entity an organization owns, usable as a scope target (entity:action).
type ScopeEntity struct {
	// The client database the entity belongs to.
	Database string `json:"database"`
	// The entity/table name — the scope's entity segment.
	Entity string `json:"entity"`
	// Table kind: data, org, relation, helper.
	Kind string `json:"kind"`
}

type ScopeGrant struct {
	ID       string `json:"id"`
	ClientID string `json:"client_id"`
	Raw      string `json:"raw"`
	// The org token from the scope, or null when the scope targets the user's personal data.
	OrganizationSlug *string `json:"organization_slug,omitempty"`
	Entity           string  `json:"entity"`
	Action           string  `json:"action"`
	Enabled          bool    `json:"enabled"`
}

type SendEmailInput struct {
	To      []string `json:"to"`
	Subject string   `json:"subject"`
	Text    string   `json:"text"`
	HTML    *string  `json:"html,omitempty"`
}

type SendEmailResult struct {
	Delivered bool `json:"delivered"`
}

type SendNotificationInput struct {
	// Recipient user id. Defaults to the calling user when omitted.
	UserID *string `json:"userId,omitempty"`
	Title  string  `json:"title"`
	Body   string  `json:"body"`
	// Optional deep link opened when the notification is tapped.
	URL *string `json:"url,omitempty"`
}

type Setting struct {
	// The client (OAuth app) the setting belongs to.
	ClientID string `json:"client_id"`
	Key      string `json:"key"`
	// JSON-encoded value.
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

// Extra profile fields the caller has agreed to share with a viewer.
type SharingGrant struct {
	Viewer *ConnectionProfile `json:"viewer"`
	Fields []string           `json:"fields"`
}

type StorageCategory struct {
	// One of: photos, videos, documents, other.
	Category string `json:"category"`
	Bytes    int    `json:"bytes"`
}

type StoragePoint struct {
	// ISO-8601 date (YYYY-MM-DD).
	Date  string `json:"date"`
	Bytes int    `json:"bytes"`
}

type StorageTier struct {
	// One of: hot, cold, archive.
	Tier                string  `json:"tier"`
	Bytes               int     `json:"bytes"`
	UnitPricePerGbMonth float64 `json:"unitPricePerGbMonth"`
	Currency            string  `json:"currency"`
}

// Storage usage for the authenticated user, broken down by file category and billing tier.
type StorageUsage struct {
	// Authoritative total bytes stored, deduplicated at the chunk level.
	TotalBytes int `json:"totalBytes"`
	// Logical size per file category (photos, videos, documents, other).
	Categories []*StorageCategory `json:"categories"`
	// Currently-stored bytes per billing tier, with the locked-in price.
	Tiers []*StorageTier `json:"tiers"`
	// Daily cumulative stored bytes over the last year, reconstructed from billing intervals.
	History []*StoragePoint `json:"history"`
}

type StringFilter struct {
	Eq         *string  `json:"eq,omitempty"`
	Ne         *string  `json:"ne,omitempty"`
	Contains   *string  `json:"contains,omitempty"`
	StartsWith *string  `json:"startsWith,omitempty"`
	EndsWith   *string  `json:"endsWith,omitempty"`
	In         []string `json:"in,omitempty"`
	// Case-sensitive regular expression (string::matches).
	Matches *string `json:"matches,omitempty"`
	// Full-text search (the @@ match operator). Requires a FULLTEXT index on the
	//   field — currently only contact.formatted_name; using it elsewhere errors.
	Search *string `json:"search,omitempty"`
	// Approximate match via string::similarity::fuzzy; tolerates typos. No index needed.
	Fuzzy  *string `json:"fuzzy,omitempty"`
	IsNull *bool   `json:"isNull,omitempty"`
}

// Filter a list of plain strings (categories / nicknames / keywords).
type StringListFilter struct {
	// Every given value must be present.
	HasAll []string `json:"hasAll,omitempty"`
	// At least one given value must be present.
	HasAny []string `json:"hasAny,omitempty"`
	// Case-insensitive substring match against any element.
	Contains *string    `json:"contains,omitempty"`
	IsEmpty  *bool      `json:"isEmpty,omitempty"`
	Size     *IntFilter `json:"size,omitempty"`
}

type TableDefInput struct {
	Name       string           `json:"name"`
	Schemafull *bool            `json:"schemafull,omitempty"`
	Fields     []*FieldDefInput `json:"fields,omitempty"`
	Indexes    []*IndexDefInput `json:"indexes,omitempty"`
	// Ownership classification. Defaults to "data" (user-scoped): a server-injected
	// subject_user_id stamps each row to the authenticated user. "internal" (org-owned)
	// rows have no per-user owner — the instance belongs to one organization, so any of
	// the org's clients read/write every row; internal writes require a confidential
	// (client_credentials) token. "relation" and "helper" tables are exempt from a
	// direct owner but must set subjectPath so they stay traceable to a user indirectly.
	Kind *string `json:"kind,omitempty"`
	// Read visibility: "private" (default — owner only), "shared" (owner plus users the
	// owner grants) or "public" (anyone, including anonymous). Ownership ("kind") and
	// visibility are independent axes.
	Visibility *string `json:"visibility,omitempty"`
	// When true, the table is rewritten into a versioned form with history endpoints.
	History *bool `json:"history,omitempty"`
	// Required for relation/helper tables: the path that traces a row back to a user (e.g. "in.subject_user_id").
	SubjectPath *string `json:"subjectPath,omitempty"`
}

type UpdateCalendarInput struct {
	Name      *string `json:"name,omitempty"`
	Color     *string `json:"color,omitempty"`
	IsDefault *bool   `json:"is_default,omitempty"`
}

// Partial update — omitted fields are left unchanged. Collection fields replace
// the whole list when present (send the full array, or [] to clear).
type UpdateContactInput struct {
	Kind          *string                     `json:"kind,omitempty"`
	FormattedName *string                     `json:"formatted_name,omitempty"`
	Name          *NameInput                  `json:"name,omitempty"`
	Nicknames     []string                    `json:"nicknames,omitempty"`
	Birthday      *string                     `json:"birthday,omitempty"`
	Anniversary   *string                     `json:"anniversary,omitempty"`
	Gender        *GenderInput                `json:"gender,omitempty"`
	Emails        []*ContactFieldInput        `json:"emails,omitempty"`
	Phones        []*ContactFieldInput        `json:"phones,omitempty"`
	Impps         []*ContactFieldInput        `json:"impps,omitempty"`
	Languages     []*ContactFieldInput        `json:"languages,omitempty"`
	Addresses     []*AddressInput             `json:"addresses,omitempty"`
	Organizations []*ContactOrganizationInput `json:"organizations,omitempty"`
	Title         *string                     `json:"title,omitempty"`
	Role          *string                     `json:"role,omitempty"`
	Timezone      *string                     `json:"timezone,omitempty"`
	Geo           *GeoInput                   `json:"geo,omitempty"`
	Categories    []string                    `json:"categories,omitempty"`
	Notes         []string                    `json:"notes,omitempty"`
	Urls          []*ContactFieldInput        `json:"urls,omitempty"`
	Source        *string                     `json:"source,omitempty"`
	Prodid        *string                     `json:"prodid,omitempty"`
	Fburl         *string                     `json:"fburl,omitempty"`
	Caluri        *string                     `json:"caluri,omitempty"`
	Caladruri     *string                     `json:"caladruri,omitempty"`
	Photo         *string                     `json:"photo,omitempty"`
	Logo          *string                     `json:"logo,omitempty"`
	Sound         *string                     `json:"sound,omitempty"`
	Key           *string                     `json:"key,omitempty"`
	CustomFields  []*CustomFieldInput         `json:"custom_fields,omitempty"`
	Favorite      *bool                       `json:"favorite,omitempty"`
	Archived      *bool                       `json:"archived,omitempty"`
}

type UpdateEventInput struct {
	CalendarID              *string                `json:"calendarId,omitempty"`
	Title                   *string                `json:"title,omitempty"`
	Description             *string                `json:"description,omitempty"`
	Start                   *string                `json:"start,omitempty"`
	Duration                *string                `json:"duration,omitempty"`
	TimeZone                *string                `json:"time_zone,omitempty"`
	ShowWithoutTime         *bool                  `json:"show_without_time,omitempty"`
	Status                  *string                `json:"status,omitempty"`
	FreeBusyStatus          *string                `json:"free_busy_status,omitempty"`
	Privacy                 *string                `json:"privacy,omitempty"`
	Priority                *int                   `json:"priority,omitempty"`
	Color                   *string                `json:"color,omitempty"`
	Keywords                []string               `json:"keywords,omitempty"`
	Participants            map[string]any         `json:"participants,omitempty"`
	Locations               map[string]any         `json:"locations,omitempty"`
	VirtualLocations        map[string]any         `json:"virtual_locations,omitempty"`
	Alerts                  map[string]any         `json:"alerts,omitempty"`
	Links                   map[string]any         `json:"links,omitempty"`
	RelatedTo               map[string]any         `json:"related_to,omitempty"`
	Localizations           map[string]any         `json:"localizations,omitempty"`
	RecurrenceOverrides     map[string]any         `json:"recurrence_overrides,omitempty"`
	RecurrenceRules         []*RecurrenceRuleInput `json:"recurrence_rules,omitempty"`
	ExcludedRecurrenceRules []*RecurrenceRuleInput `json:"excluded_recurrence_rules,omitempty"`
}

// Partial update — omitted fields are left unchanged.
type UpdateMemoryInput struct {
	Title      *string `json:"title,omitempty"`
	SourceText *string `json:"sourceText,omitempty"`
}

type UpdateOrganizationInput struct {
	Name         *string `json:"name,omitempty"`
	Description  *string `json:"description,omitempty"`
	LogoURL      *string `json:"logo_url,omitempty"`
	BillingEmail *string `json:"billing_email,omitempty"`
}

// One instance-level usage sample (CPU / memory / storage) at a point in time.
type UsagePoint struct {
	SampledAt  string  `json:"sampled_at"`
	CPUPercent float64 `json:"cpu_percent"`
	// Bytes are Float to stay within GraphQL's 32-bit Int range.
	MemBytes     float64 `json:"mem_bytes"`
	MemPercent   float64 `json:"mem_percent"`
	StorageBytes float64 `json:"storage_bytes"`
}

// A user surfaced by search for inviting; name-only, plus any existing status.
type UserSearchResult struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	// null = no connection, else pending | accepted | blocked.
	ConnectionStatus *string `json:"connection_status,omitempty"`
}

// Which set of contacts to return. ACTIVE excludes archived and trashed.
type ContactScope string

const (
	ContactScopeActive   ContactScope = "ACTIVE"
	ContactScopeArchived ContactScope = "ARCHIVED"
	ContactScopeTrashed  ContactScope = "TRASHED"
	ContactScopeAll      ContactScope = "ALL"
)

var AllContactScope = []ContactScope{
	ContactScopeActive,
	ContactScopeArchived,
	ContactScopeTrashed,
	ContactScopeAll,
}

func (e ContactScope) IsValid() bool {
	switch e {
	case ContactScopeActive, ContactScopeArchived, ContactScopeTrashed, ContactScopeAll:
		return true
	}
	return false
}

func (e ContactScope) String() string {
	return string(e)
}

func (e *ContactScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContactScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContactScope", str)
	}
	return nil
}

func (e ContactScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContactScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContactScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Sortable contact columns (whitelisted; arbitrary fields aren't allowed).
type ContactSortField string

const (
	ContactSortFieldFormattedName ContactSortField = "FORMATTED_NAME"
	ContactSortFieldCreatedAt     ContactSortField = "CREATED_AT"
	ContactSortFieldUpdatedAt     ContactSortField = "UPDATED_AT"
	ContactSortFieldBirthday      ContactSortField = "BIRTHDAY"
)

var AllContactSortField = []ContactSortField{
	ContactSortFieldFormattedName,
	ContactSortFieldCreatedAt,
	ContactSortFieldUpdatedAt,
	ContactSortFieldBirthday,
}

func (e ContactSortField) IsValid() bool {
	switch e {
	case ContactSortFieldFormattedName, ContactSortFieldCreatedAt, ContactSortFieldUpdatedAt, ContactSortFieldBirthday:
		return true
	}
	return false
}

func (e ContactSortField) String() string {
	return string(e)
}

func (e *ContactSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContactSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContactSortField", str)
	}
	return nil
}

func (e ContactSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContactSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContactSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Sortable media columns (whitelisted).
type MediaSortField string

const (
	MediaSortFieldFilename    MediaSortField = "FILENAME"
	MediaSortFieldCreatedAt   MediaSortField = "CREATED_AT"
	MediaSortFieldUpdatedAt   MediaSortField = "UPDATED_AT"
	MediaSortFieldSize        MediaSortField = "SIZE"
	MediaSortFieldCaptureDate MediaSortField = "CAPTURE_DATE"
)

var AllMediaSortField = []MediaSortField{
	MediaSortFieldFilename,
	MediaSortFieldCreatedAt,
	MediaSortFieldUpdatedAt,
	MediaSortFieldSize,
	MediaSortFieldCaptureDate,
}

func (e MediaSortField) IsValid() bool {
	switch e {
	case MediaSortFieldFilename, MediaSortFieldCreatedAt, MediaSortFieldUpdatedAt, MediaSortFieldSize, MediaSortFieldCaptureDate:
		return true
	}
	return false
}

func (e MediaSortField) String() string {
	return string(e)
}

func (e *MediaSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaSortField", str)
	}
	return nil
}

func (e MediaSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MemorySortField string

const (
	MemorySortFieldCreatedAt MemorySortField = "CREATED_AT"
	MemorySortFieldUpdatedAt MemorySortField = "UPDATED_AT"
	MemorySortFieldTitle     MemorySortField = "TITLE"
)

var AllMemorySortField = []MemorySortField{
	MemorySortFieldCreatedAt,
	MemorySortFieldUpdatedAt,
	MemorySortFieldTitle,
}

func (e MemorySortField) IsValid() bool {
	switch e {
	case MemorySortFieldCreatedAt, MemorySortFieldUpdatedAt, MemorySortFieldTitle:
		return true
	}
	return false
}

func (e MemorySortField) String() string {
	return string(e)
}

func (e *MemorySortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MemorySortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MemorySortField", str)
	}
	return nil
}

func (e MemorySortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MemorySortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MemorySortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
