// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql_model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Album struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	// Number of file in the album.
	Count int `json:"count"`
	// Thumbnail file id of the most-recently-added member, or null when empty.
	//   Use it for the album card; null renders a placeholder cover.
	CoverThumbnailID *string `json:"coverThumbnailId,omitempty"`
}

type BoolFilter struct {
	Eq *bool `json:"eq,omitempty"`
}

type ClientDatabase struct {
	ID        string `json:"id"`
	ClientID  string `json:"client_id"`
	Name      string `json:"name"`
	DbName    string `json:"db_name"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// A connection edge as seen by the caller.
type Connection struct {
	// The other user in the connection (never the caller).
	User   *ConnectionProfile `json:"user"`
	Status string             `json:"status"`
	// Relative to the caller: "outgoing" (caller requested) or "incoming".
	Direction string `json:"direction"`
	CreatedAt string `json:"created_at"`
}

// A user profile projected to only the fields the caller may see. Name is always
// visible between accepted connections; email/avatar_url are null unless a sharing
// grant permits them.
type ConnectionProfile struct {
	ID        string  `json:"id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Email     *string `json:"email,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
}

// Returned once on creation. db_password is shown only once — store it securely.
type CreateClientDatabaseResult struct {
	Database   *ClientDatabase `json:"database"`
	DbPassword string          `json:"db_password"`
}

type CreateClientInput struct {
	// Used as both the OAuth client_id and the SurrealDB record key.
	// Must be unique across all clients (e.g. "myapp.example.com").
	ID string `json:"id"`
	// The organization that will own this client. The caller must be a member of it.
	OrganizationID string `json:"organizationId"`
	// Human-readable display name shown in first-party UI (e.g. the Vault).
	Name         *string  `json:"name,omitempty"`
	RedirectUris []string `json:"redirect_uris"`
	// Scopes this client is allowed to request.
	Scopes []string `json:"scopes"`
	// When true, the consent screen is skipped and scopes are granted automatically.
	// Intended for first-party apps where the user owns both the app and the resource.
	AutoGrantScopes *bool `json:"auto_grant_scopes,omitempty"`
	// When true, no secret is generated. The client authenticates via PKCE only.
	// Suitable for SPAs and native apps that cannot safely store a secret.
	Public *bool `json:"public,omitempty"`
}

// Returned once on creation. secret is null for public (PKCE-only) clients.
type CreateClientResult struct {
	Client *OAuthClient `json:"client"`
	// null for public clients
	Secret *string `json:"secret,omitempty"`
}

type CreateOrganizationInput struct {
	Name string `json:"name"`
	// Used as the organization token in scopes (e.g. "org_123"). Must be unique.
	Slug         string  `json:"slug"`
	Description  *string `json:"description,omitempty"`
	BillingEmail *string `json:"billing_email,omitempty"`
}

// Internal compiled representation of a client schema. Clients no longer submit this
// directly — they author in the OpenSchema DSL (`schemaSource`), which the server
// compiles into this shape before generating SurrealQL DDL.
type DatabaseSchemaInput struct {
	Tables []*TableDefInput `json:"tables"`
}

type DatabaseUsage struct {
	Current        *DatabaseUsageCurrent `json:"current"`
	InstanceSeries []*UsagePoint         `json:"instanceSeries"`
	QuerySeries    []*QueryUsagePoint    `json:"querySeries"`
}

// Latest snapshot shown as gauges.
type DatabaseUsageCurrent struct {
	CPUPercent        float64 `json:"cpu_percent"`
	MemBytes          float64 `json:"mem_bytes"`
	MemPercent        float64 `json:"mem_percent"`
	StorageBytes      float64 `json:"storage_bytes"`
	AvgLatencyMs      float64 `json:"avg_latency_ms"`
	ActiveConnections int     `json:"active_connections"`
	QueryCount        int     `json:"query_count"`
}

// Operators for a real datetime field (created_at / updated_at / start). String
// values are ISO-8601 instants; `withinLast` is a SurrealDB duration like `30d`.
type DateFilter struct {
	Eq         *string `json:"eq,omitempty"`
	Before     *string `json:"before,omitempty"`
	After      *string `json:"after,omitempty"`
	WithinLast *string `json:"withinLast,omitempty"`
}

type FieldDefInput struct {
	Name string `json:"name"`
	// Allowed base types: string, int, float, decimal, bool, datetime, duration, bytes, uuid, object, any.
	// Parameterized: option<T>, array<T>, set<T> (recursively).
	Type string `json:"type"`
}

type File struct {
	ID        string `json:"id"`
	Filename  string `json:"filename"`
	MimeType  string `json:"mime_type"`
	Size      int    `json:"size"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	// The linked thumbnail file id, if one was generated. Load this for grids;
	//   load the original (id) only for fullsize viewing.
	ThumbnailID *string `json:"thumbnailId,omitempty"`
	// Embedding lifecycle for visual/text search: pending | ready | failed | none.
	EmbeddingStatus *string `json:"embeddingStatus,omitempty"`
	// Original capture time from the photo's EXIF (DateTimeOriginal), if present.
	//   Distinct from created_at, which is when the upload reached the server.
	CaptureDate *string `json:"captureDate,omitempty"`
	// GPS coordinate from the photo's EXIF, if present. Stored unencrypted.
	Location *GeoPoint `json:"location,omitempty"`
	// Full parsed EXIF tag set, stored unencrypted. Shape varies by camera.
	Exif map[string]any `json:"exif,omitempty"`
	// True when the caller has favorited this file (per-user, resolved via a
	//   file_favorite subquery — like embeddingStatus).
	Favorite bool `json:"favorite"`
}

type FileFilter struct {
	Filename    *StringFilter `json:"filename,omitempty"`
	MimeType    *StringFilter `json:"mime_type,omitempty"`
	Size        *IntFilter    `json:"size,omitempty"`
	CreatedAt   *DateFilter   `json:"created_at,omitempty"`
	UpdatedAt   *DateFilter   `json:"updated_at,omitempty"`
	CaptureDate *DateFilter   `json:"captureDate,omitempty"`
	Location    *GeoFilter    `json:"location,omitempty"`
	And         []*FileFilter `json:"and,omitempty"`
	Or          []*FileFilter `json:"or,omitempty"`
	Not         *FileFilter   `json:"not,omitempty"`
}

// One sort key. Pass a list to sort by several columns in order.
type FileSort struct {
	Field     FileSortField  `json:"field"`
	Direction *SortDirection `json:"direction,omitempty"`
}

// Geo predicates against a GEO point (lat/lng).
type GeoFilter struct {
	// Within radiusMeters of the given point (haversine, metres).
	Near *NearInput `json:"near,omitempty"`
	// GeoJSON geometry (e.g. a Polygon). The point must fall inside it.
	Within map[string]any `json:"within,omitempty"`
	IsNull *bool          `json:"isNull,omitempty"`
}

// A GPS coordinate (decimal degrees).
type GeoPoint struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type IndexDefInput struct {
	Name   string   `json:"name"`
	Fields []string `json:"fields"`
	Unique *bool    `json:"unique,omitempty"`
	// When true, the index is a FULLTEXT (BM25) index instead of a plain/unique one,
	// enabling the `search` argument on the table's list query. Only valid on string
	// fields. `unique` is ignored for fulltext indexes.
	Fulltext *bool `json:"fulltext,omitempty"`
	// Analyzer for a fulltext index. Defaults to the built-in "text_en".
	Analyzer *string `json:"analyzer,omitempty"`
}

type IntFilter struct {
	Eq *int `json:"eq,omitempty"`
	Gt *int `json:"gt,omitempty"`
	Lt *int `json:"lt,omitempty"`
}

// How the caller handles calendar invites from a specific user.
type InvitePolicy struct {
	// The other user the policy applies to.
	User *ConnectionProfile `json:"user"`
	// "block" | "auto_accept".
	Policy string `json:"policy"`
}

// One ordered migration step for a client database. Apply `schema` (declarative
// DDL, idempotent) and/or `statements` (imperative SurrealQL, e.g. data backfills).
// Each version runs at most once; the server records applied versions per database.
type MigrationInput struct {
	// Monotonic version. Only versions greater than the database's current version run.
	Version int    `json:"version"`
	Name    string `json:"name"`
	// Optional OpenSchema DSL applied at this version (compiled to DDL, idempotent).
	SchemaSource *string `json:"schemaSource,omitempty"`
	// Optional imperative SurrealQL statements (run as admin against this database).
	Statements []string `json:"statements,omitempty"`
}

type MigrationResult struct {
	// Versions applied by this call, in order.
	Applied []int `json:"applied"`
	// The database's version after this call.
	CurrentVersion int `json:"currentVersion"`
}

type Mutation struct {
}

// A centre point plus radius for proximity search.
type NearInput struct {
	Lat          float64 `json:"lat"`
	Lng          float64 `json:"lng"`
	RadiusMeters float64 `json:"radiusMeters"`
}

type Notification struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Body      string  `json:"body"`
	URL       *string `json:"url,omitempty"`
	Read      bool    `json:"read"`
	CreatedAt string  `json:"created_at"`
}

type OAuthClient struct {
	ID string `json:"id"`
	// Human-readable display name, shown in first-party UI (e.g. the Vault).
	Name *string `json:"name,omitempty"`
	// Scopes this client is allowed to request.
	Scopes       []string `json:"scopes"`
	RedirectUris []string `json:"redirect_uris"`
	// True = PKCE-only; client has no secret.
	Public bool `json:"public"`
	// True = consent screen is skipped; scopes granted automatically.
	AutoGrantScopes bool `json:"auto_grant_scopes"`
}

// An organization's billing / payment-method state.
type OrgBillingStatus struct {
	// One of none, pending, valid, invalid.
	Status string `json:"status"`
	// True once a reusable payment mandate has been captured.
	HasPaymentMethod bool `json:"has_payment_method"`
}

type OrgInvite struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type Organization struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Slug         string  `json:"slug"`
	Description  *string `json:"description,omitempty"`
	LogoURL      *string `json:"logo_url,omitempty"`
	BillingEmail *string `json:"billing_email,omitempty"`
	// Hosting plan: "free" (shared instance) or "pro" (dedicated database).
	Plan      string `json:"plan"`
	CreatedAt string `json:"created_at"`
}

type OrganizationMember struct {
	UserID string `json:"user_id"`
	// Display name for the member (display name, full name, or email).
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Role  string  `json:"role"`
}

// Result of starting Mollie payment-method setup for an organization.
type PaymentSetup struct {
	// Hosted Mollie checkout the caller must be redirected to.
	CheckoutURL string `json:"checkout_url"`
}

type Query struct {
}

// One per-database query sample at a point in time.
type QueryUsagePoint struct {
	SampledAt         string  `json:"sampled_at"`
	QueryCount        int     `json:"query_count"`
	AvgLatencyMs      float64 `json:"avg_latency_ms"`
	ActiveConnections int     `json:"active_connections"`
}

type RefreshToken struct {
	ID        string       `json:"id"`
	Client    *OAuthClient `json:"client"`
	Scopes    []string     `json:"scopes"`
	ExpiresAt string       `json:"expires_at"`
	CreatedAt string       `json:"created_at"`
	Revoked   bool         `json:"revoked"`
	Used      bool         `json:"used"`
}

// A data entity an organization owns, usable as a scope target (entity:action).
type ScopeEntity struct {
	// The client database the entity belongs to.
	Database string `json:"database"`
	// The entity/table name — the scope's entity segment.
	Entity string `json:"entity"`
	// Table kind: data, org, relation, helper.
	Kind string `json:"kind"`
}

type ScopeGrant struct {
	ID       string `json:"id"`
	ClientID string `json:"client_id"`
	Raw      string `json:"raw"`
	// The org token from the scope, or null when the scope targets the user's personal data.
	OrganizationSlug *string `json:"organization_slug,omitempty"`
	Entity           string  `json:"entity"`
	Action           string  `json:"action"`
	Enabled          bool    `json:"enabled"`
}

type SendEmailInput struct {
	To      []string `json:"to"`
	Subject string   `json:"subject"`
	Text    string   `json:"text"`
	HTML    *string  `json:"html,omitempty"`
}

type SendEmailResult struct {
	Delivered bool `json:"delivered"`
}

type SendNotificationInput struct {
	// Recipient user id. Defaults to the calling user when omitted.
	UserID *string `json:"userId,omitempty"`
	Title  string  `json:"title"`
	Body   string  `json:"body"`
	// Optional deep link opened when the notification is tapped.
	URL *string `json:"url,omitempty"`
}

type Setting struct {
	// The client (OAuth app) the setting belongs to.
	ClientID string `json:"client_id"`
	Key      string `json:"key"`
	// JSON-encoded value.
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

// Extra profile fields the caller has agreed to share with a viewer.
type SharingGrant struct {
	Viewer *ConnectionProfile `json:"viewer"`
	Fields []string           `json:"fields"`
}

type StorageCategory struct {
	// One of: photos, videos, documents, other.
	Category string `json:"category"`
	Bytes    int    `json:"bytes"`
}

type StoragePoint struct {
	// ISO-8601 date (YYYY-MM-DD).
	Date  string `json:"date"`
	Bytes int    `json:"bytes"`
}

type StorageTier struct {
	// One of: hot, cold, archive.
	Tier                string  `json:"tier"`
	Bytes               int     `json:"bytes"`
	UnitPricePerGbMonth float64 `json:"unitPricePerGbMonth"`
	Currency            string  `json:"currency"`
}

// Storage usage for the authenticated user, broken down by file category and billing tier.
type StorageUsage struct {
	// Authoritative total bytes stored, deduplicated at the chunk level.
	TotalBytes int `json:"totalBytes"`
	// Logical size per file category (photos, videos, documents, other).
	Categories []*StorageCategory `json:"categories"`
	// Currently-stored bytes per billing tier, with the locked-in price.
	Tiers []*StorageTier `json:"tiers"`
	// Daily cumulative stored bytes over the last year, reconstructed from billing intervals.
	History []*StoragePoint `json:"history"`
}

type StringFilter struct {
	Eq         *string  `json:"eq,omitempty"`
	Ne         *string  `json:"ne,omitempty"`
	Contains   *string  `json:"contains,omitempty"`
	StartsWith *string  `json:"startsWith,omitempty"`
	EndsWith   *string  `json:"endsWith,omitempty"`
	In         []string `json:"in,omitempty"`
	// Case-sensitive regular expression (string::matches).
	Matches *string `json:"matches,omitempty"`
	// Full-text search (the @@ match operator). Requires a FULLTEXT index on the
	//   field — currently only contact.formatted_name; using it elsewhere errors.
	Search *string `json:"search,omitempty"`
	// Approximate match via string::similarity::fuzzy; tolerates typos. No index needed.
	Fuzzy  *string `json:"fuzzy,omitempty"`
	IsNull *bool   `json:"isNull,omitempty"`
}

// Filter a list of plain strings (categories / nicknames / keywords).
type StringListFilter struct {
	// Every given value must be present.
	HasAll []string `json:"hasAll,omitempty"`
	// At least one given value must be present.
	HasAny []string `json:"hasAny,omitempty"`
	// Case-insensitive substring match against any element.
	Contains *string    `json:"contains,omitempty"`
	IsEmpty  *bool      `json:"isEmpty,omitempty"`
	Size     *IntFilter `json:"size,omitempty"`
}

type TableDefInput struct {
	Name       string           `json:"name"`
	Schemafull *bool            `json:"schemafull,omitempty"`
	Fields     []*FieldDefInput `json:"fields,omitempty"`
	Indexes    []*IndexDefInput `json:"indexes,omitempty"`
	// Ownership classification. Defaults to "data" (user-scoped): a server-injected
	// subject_user_id stamps each row to the authenticated user. "internal" (org-owned)
	// rows have no per-user owner — the instance belongs to one organization, so any of
	// the org's clients read/write every row; internal writes require a confidential
	// (client_credentials) token. "relation" and "helper" tables are exempt from a
	// direct owner but must set subjectPath so they stay traceable to a user indirectly.
	Kind *string `json:"kind,omitempty"`
	// Read visibility: "private" (default — owner only), "shared" (owner plus users the
	// owner grants) or "public" (anyone, including anonymous). Ownership ("kind") and
	// visibility are independent axes.
	Visibility *string `json:"visibility,omitempty"`
	// When true, the table is rewritten into a versioned form with history endpoints.
	History *bool `json:"history,omitempty"`
	// Required for relation/helper tables: the path that traces a row back to a user (e.g. "in.subject_user_id").
	SubjectPath *string `json:"subjectPath,omitempty"`
}

type UpdateOrganizationInput struct {
	Name         *string `json:"name,omitempty"`
	Description  *string `json:"description,omitempty"`
	LogoURL      *string `json:"logo_url,omitempty"`
	BillingEmail *string `json:"billing_email,omitempty"`
}

// One instance-level usage sample (CPU / memory / storage) at a point in time.
type UsagePoint struct {
	SampledAt  string  `json:"sampled_at"`
	CPUPercent float64 `json:"cpu_percent"`
	// Bytes are Float to stay within GraphQL's 32-bit Int range.
	MemBytes     float64 `json:"mem_bytes"`
	MemPercent   float64 `json:"mem_percent"`
	StorageBytes float64 `json:"storage_bytes"`
}

// A user surfaced by search for inviting; name-only, plus any existing status.
type UserSearchResult struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	// null = no connection, else pending | accepted | blocked.
	ConnectionStatus *string `json:"connection_status,omitempty"`
}

// Sortable file columns (whitelisted).
type FileSortField string

const (
	FileSortFieldFilename    FileSortField = "FILENAME"
	FileSortFieldCreatedAt   FileSortField = "CREATED_AT"
	FileSortFieldUpdatedAt   FileSortField = "UPDATED_AT"
	FileSortFieldSize        FileSortField = "SIZE"
	FileSortFieldCaptureDate FileSortField = "CAPTURE_DATE"
)

var AllFileSortField = []FileSortField{
	FileSortFieldFilename,
	FileSortFieldCreatedAt,
	FileSortFieldUpdatedAt,
	FileSortFieldSize,
	FileSortFieldCaptureDate,
}

func (e FileSortField) IsValid() bool {
	switch e {
	case FileSortFieldFilename, FileSortFieldCreatedAt, FileSortFieldUpdatedAt, FileSortFieldSize, FileSortFieldCaptureDate:
		return true
	}
	return false
}

func (e FileSortField) String() string {
	return string(e)
}

func (e *FileSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FileSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FileSortField", str)
	}
	return nil
}

func (e FileSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FileSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FileSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
